const movieData = {
	"Inception": {
		title: "Inception",
		year: 2010,
		runtime: "2h 28m",
		genres: ["Action", "Sci-Fi", "Thriller"],
		director: "Christopher Nolan",
		cast: ["Leonardo DiCaprio", "Joseph Gordon-Levitt", "Elliot Page"],
		franchise: null,
		keywords: ["Dream", "Heist", "Mind-bending"],
		ageRating: "12A",
		rating: "8.8/10",
		desc: "A skilled thief who steals secrets through dream-sharing technology is given the inverse task of planting an idea into the mind of a C.E.O.",
		similar: ["TheMatrix", "Interstellar", "Tenet"],
		sequels: [],
        poster: "movies/inception/Inception.jpg",
        link: "https://www.warnerbros.com/movies/inception",
        trailer: "YoHD9XEInc0" // Inception Trailer
	},
	"TheMatrix": {
		title: "The Matrix",
		year: 1999,
		runtime: "2h 16m",
		genres: ["Action", "Sci-Fi"],
		director: "The Wachowskis",
		cast: ["Keanu Reeves", "Laurence Fishburne", "Carrie-Anne Moss"],
		franchise: "Matrix",
		keywords: ["Simulation", "Dystopian", "Kung Fu"],
		ageRating: "15",
		rating: "8.7/10",
		desc: "A hacker discovers the shocking truth about reality and his role in the war against its controllers.",
		similar: ["Inception", "Dark City", "Equilibrium"],
		sequels: ["TheMatrix2", "TheMatrix3", "TheMatrix4"],
        poster: "movies/matrix/The Matrix.jpg",
        link: "https://www.warnerbros.com/movies/matrix",
        trailer: "vKQi3bBA1y8" // Matrix Trailer
	},
	"TheMatrix2": {
		title: "The Matrix Reloaded",
		year: 2003,
		runtime: "2h 18m",
		genres: ["Action", "Sci-Fi"],
		director: "The Wachowskis",
		cast: ["Keanu Reeves", "Laurence Fishburne", "Carrie-Anne Moss"],
		franchise: "Matrix",
		keywords: ["Simulation", "Dystopian", "Kung Fu"],
		ageRating: "15",
		rating: "8.6/10",
		desc: "A liberating hero races to uncover deeper layers of control, confronting new foes and revelations that challenge everything he believes about fate and freedom.",
		similar: ["Inception", "Dark City", "Equilibrium"],
		sequels: ["TheMatrix", "TheMatrix3", "TheMatrix4"],
        poster: "movies/matrix/The Matrix2.jpg",
        link: "https://www.warnerbros.com/movies/matrix-reloaded",
        trailer: "kYzz0FSgpSU"
	},
	"TheMatrix3": {
		title: "The Matrix Revolutions",
		year: 2003,
		runtime: "2h 09m",
		genres: ["Action", "Sci-Fi"],
		director: "The Wachowskis",
		cast: ["Keanu Reeves", "Laurence Fishburne", "Carrie-Anne Moss"],
		franchise: "Matrix",
		keywords: ["Simulation", "Dystopian", "Kung Fu"],
		ageRating: "15",
		rating: "8.8/10",
		desc: "As the war reaches its breaking point, a chosen fighter battles on two fronts—both human and machine—to forge a final path toward peace.",
		similar: ["Inception", "Dark City", "Equilibrium"],
		sequels: ["TheMatrix", "TheMatrix2", "TheMatrix4"],
        poster: "movies/matrix/The Matrix3.jpg",
        link: "https://www.warnerbros.com/movies/matrix-revolutions",
        trailer: "hMbexEPAOQI"
	},
	"TheMatrix4": {
		title: "The Matrix Resurrections",
		year: 2021,
		runtime: "2h 28m",
		genres: ["Action", "Sci-Fi"],
		director: "The Wachowskis",
		cast: ["Keanu Reeves", "Laurence Fishburne", "Carrie-Anne Moss"],
		franchise: "Matrix",
		keywords: ["Simulation", "Dystopian", "Kung Fu"],
		ageRating: "15",
		rating: "5.9/10",
		desc: "Drawn back into a reality he once escaped, a weary legend confronts illusions, lost memories, and a renewed struggle for truth in a world more deceptive than ever.",
		similar: ["Inception", "Dark City", "Equilibrium"],
		sequels: ["TheMatrix", "TheMatrix2", "TheMatrix3"],
        poster: "movies/matrix/The Matrix4.jpg",
        link: "https://www.warnerbros.com/movies/matrix-resurrections",
        trailer: "9ix7TUGnRIo"
	},
	"HarryPotter1": {
		title: "Harry Potter and the Philosopher's Stone",
		year: 2001,
		runtime: "2h 32m",
		genres: ["Fantasy", "Action", "Adventure"],
		director: "Chris Columbus",
		cast: ["Daniel Radcliffe", "Emma Watson", "Rupert Grint"],
		franchise: "HarryPotter",
		keywords: ["Magic", "School", "Wizards"],
		ageRating: "PG",
		rating: "9.6/10",
		desc: "A young wizard discovers a hidden power within his school, drawing him into a perilous quest for an artifact of immortality.",
		similar: [],
		sequels: ["HarryPotter2", "HarryPotter3", "HarryPotter4", "HarryPotter5", "HarryPotter6","HarryPotter7","HarryPotter8"],
        poster: "movies/harrypotter/hp1.jpg",
        link: "https://www.wizardingworld.com",
        trailer: "VyHV0BR_toI"
	},
	"HarryPotter2": {
		title: "Harry Potter and the Chamber of Secrets",
		year: 2002,
		runtime: "2h 38m",
		genres: ["Fantasy", "Action", "Adventure"],
		director: "Chris Columbus",
		cast: ["Daniel Radcliffe", "Emma Watson", "Rupert Grint"],
		franchise: "HarryPotter",
		keywords: ["Magic", "School", "Mystery"],
		ageRating: "PG",
		rating: "9.4/10",
		desc: "A young wizard confronts an ancient chamber within his school, unraveling a sinister mystery bound to a dark legacy.",
		similar: [],
		sequels: ["HarryPotter1", "HarryPotter3", "HarryPotter4", "HarryPotter5", "HarryPotter6","HarryPotter7","HarryPotter8"],
        poster: "movies/harrypotter/hp2.jpg",
        link: "https://www.wizardingworld.com",
        trailer: "1bq0qff4iF8"
	},
	"HarryPotter3": {
		title: "Harry Potter and the Prisoner of Azkaban",
		year: 2004,
		runtime: "2h 22m",
		genres: ["Fantasy", "Action", "Adventure"],
		director: "Alfonso Cuarón",
		cast: ["Daniel Radcliffe", "Emma Watson", "Rupert Grint"],
		franchise: "HarryPotter",
		keywords: ["Magic", "Time Travel", "Werewolf"],
		ageRating: "PG",
		rating: "9.6/10",
		desc: "A young wizard faces ominous omens and a fugitive’s escape, uncovering secrets that will alter his understanding of the past.",
		similar: [],
		sequels: ["HarryPotter1", "HarryPotter2", "HarryPotter4", "HarryPotter5", "HarryPotter6","HarryPotter7","HarryPotter8"],
        poster: "movies/harrypotter/hp3.jpg",
        link: "https://www.wizardingworld.com",
        trailer: "lAxgztbYDbs"
	},
	"HarryPotter4": {
		title: "Harry Potter and the Goblet of Fire",
		year: 2005,
		runtime: "2h 37m",
		genres: ["Fantasy", "Action", "Adventure"],
		director: "Mike Newell",
		cast: ["Daniel Radcliffe", "Emma Watson", "Rupert Grint"],
		franchise: "HarryPotter",
		keywords: ["Magic", "Tournament", "Dark Lord"],
		ageRating: "12A",
		rating: "8.6/10",
		desc: "Thrust into a perilous tournament, a young wizard confronts deadly challenges and a dark resurgence that signals the return of an ancient threat.",
		similar: [],
		sequels: ["HarryPotter1", "HarryPotter2", "HarryPotter3", "HarryPotter5", "HarryPotter6","HarryPotter7","HarryPotter8"],
        poster: "movies/harrypotter/hp4.jpg",
        link: "https://www.wizardingworld.com",
        trailer: "3EGojp4Hh6I"
	},
	"HarryPotter5": {
		title: "Harry Potter and the Order of the Phoenix",
		year: 2007,
		runtime: "2h 18m",
		genres: ["Fantasy", "Action", "Adventure"],
		director: "David Yates",
		cast: ["Daniel Radcliffe", "Emma Watson", "Rupert Grint"],
		franchise: "HarryPotter",
		keywords: ["Magic", "Rebellion", "Prophecy"],
		ageRating: "12A",
		rating: "8.7/10",
		desc: "Haunted by visions and disbelief, a young wizard rallies allies against hidden tyranny as a shadowy power tightens its grip on the wizarding world.",
		similar: [],
		sequels: ["HarryPotter1", "HarryPotter2", "HarryPotter3", "HarryPotter4","HarryPotter6","HarryPotter7","HarryPotter8"],
        poster: "movies/harrypotter/hp5.jpg",
        link: "https://www.wizardingworld.com",
        trailer: "y6ZW7KXaXYk"
	},
	"HarryPotter6": {
		title: "Harry Potter and the Half-Blood Prince",
		year: 2009,
		runtime: "2h 33m",
		genres: ["Fantasy", "Action", "Adventure"],
		director: "David Yates",
		cast: ["Daniel Radcliffe", "Emma Watson", "Rupert Grint"],
		franchise: "HarryPotter",
		keywords: ["Magic", "Romance", "Horcruxes"],
		ageRating: "12A",
		rating: "8.7/10",
		desc: "As darkness spreads beyond the shadows, a young wizard delves into a mysterious textbook and buried memories, uncovering a path that leads ever closer to a rising evil’s true power.",
		similar: [],
		sequels: ["HarryPotter1", "HarryPotter2", "HarryPotter3", "HarryPotter4","HarryPotter5","HarryPotter7","HarryPotter8"],
		poster: "movies/harrypotter/hp6.jpg",
        link: "https://www.wizardingworld.com",
        trailer: "JYLdTuL9Wjw"
	},
	"HarryPotter7": {
		title: "Harry Potter and the Deathly Hallows: Part 1",
		year: 2010,
		runtime: "2h 26m",
		genres: ["Fantasy", "Action", "Adventure"],
		director: "David Yates",
		cast: ["Daniel Radcliffe", "Emma Watson", "Rupert Grint"],
		franchise: "HarryPotter",
		keywords: ["Magic", "Journey", "War"],
		ageRating: "12A",
		rating: "8.5/10",
		desc: "On the run from a tightening regime, three young wizards hunt for elusive relics, confronting betrayal, sacrifice, and the looming dread of a world slipping into darkness.",
		similar: [],
		sequels: ["HarryPotter1", "HarryPotter2", "HarryPotter3", "HarryPotter4","HarryPotter5","HarryPotter6","HarryPotter8"],
		poster: "movies/harrypotter/hp7.jpg",
        link: "https://www.wizardingworld.com",
        trailer: "MxqsmsA8y5k"
	},
	"HarryPotter8": {
		title: "Harry Potter and the Deathly Hallows: Part 2",
		year: 2011,
		runtime: "2h 10m",
		genres: ["Fantasy", "Action", "Adventure"],
		director: "David Yates",
		cast: ["Daniel Radcliffe", "Emma Watson", "Rupert Grint"],
		franchise: "HarryPotter",
		keywords: ["Magic", "Battle", "Finale"],
		ageRating: "12A",
		rating: "8.5/10",
		desc: "In a final clash between hope and tyranny, a young wizard returns to where it all began, facing destiny, loss, and the ultimate battle that will decide the fate of the wizarding world.",
		similar: [],
		sequels: ["HarryPotter1", "HarryPotter2", "HarryPotter3", "HarryPotter4","HarryPotter5","HarryPotter6","HarryPotter7"],
		poster: "movies/harrypotter/hp8.jpg",
        link: "https://www.wizardingworld.com",
        trailer: "mObK5XD8udk"
	},
	"Interstellar": {
		title: "Interstellar",
		year: 2014,
		runtime: "2h 49m",
		genres: ["Thriller", "Sci-Fi", "Adventure"],
		director: "Christopher Nolan",
		cast: ["Matthew McConaughey", "Jessica Chastain", "Anne Hathaway", "Mackenzie Foy", "Matt Damon", "Michael Caine"],
		franchise: null,
		keywords: ["Space", "Black Hole", "Time"],
		ageRating: "12A",
		rating: "9.2/10",
		desc: "When Earth becomes uninhabitable in the future, a farmer and ex-NASA pilot, Joseph Cooper, is tasked to pilot a spacecraft, along with a team of researchers, to find a new planet for humans.",
		similar: ["Inception", "Tenet"],
		sequels: [],
        poster: "movies/interstellar/Interstellar.jpg",
        link: "https://www.paramountmovies.com/movies/interstellar",
        trailer: "zSWdZVtXT7E"
	},
	"Tenet": {
		title: "Tenet",
		year: 2020,
		runtime: "2h 30m",
		genres: ["Action", "Sci-Fi", "Thriller"],
		director: "Christopher Nolan",
		cast: ["John David Washington", "Robert Pattinson", "Elizabeth Debicki"],
		franchise: null,
		keywords: ["Time", "Espionage", "Entropy"],
		ageRating: "12A",
		rating: "7.2/10",
		desc: "Armed with only one word, Tenet, and fighting for the survival of the entire world, a Protagonist journeys through a twilight world of international espionage on a mission that will unfold in something beyond real time.",
		similar: ["Inception", "Interstellar", "TheMatrix"],
		sequels: [],
        poster: "movies/tenet/Tenet.jpg",
        link: "https://www.warnerbros.com/movies/tenet",
        trailer: "LdOM0x0XDMo"
	},
	"TheDarkKnight2": {
		title: "The Dark Knight",
		year: 2008,
		runtime: "2h 32m",
		genres: ["Action", "Drama", "Crime", "Superhero"],
		director: "Christopher Nolan",
		cast: ["Christian Bale", "Heath Ledger", "Gary Oldman", "Aaron Eckhart", "Michael Caine", "Morgan Freeman"],
		franchise: "DarkKnightTrilogy",
		keywords: ["Hero", "Chaos", "Villain"],
		ageRating: "12A",
		rating: "9.2/10",
		desc: "When a menace known as the Joker wreaks havoc and chaos on the people of Gotham, Batman, James Gordon and Harvey Dent must work together to put an end to the madness.",
		similar: ["Tenet", "TheBatman", "BatmanSuperman", "SuicideSquad1"],
		sequels: ["TheDarkKnight1","TheDarkKnight3"],
        poster: "movies/darkknight/darkknight2.jpg",
        link: "https://www.warnerbros.com/movies/dark-knight",
        trailer: "EXeTwQWrcwY"
	},
	"TheDarkKnight1": {
		title: "Batman Begins",
		year: 2005,
		runtime: "2h 20m",
		genres: ["Action", "Drama", "Crime", "Superhero"],
		director: "Christopher Nolan",
		cast: ["Christian Bale", "Katie Holmes", "Cillian Murphy", "Liam Neeson", "Michael Caine", "Morgan Freeman"],
		franchise: "DarkKnightTrilogy",
		keywords: ["Hero", "Chaos", "Villain"],
		ageRating: "12A",
		rating: "8.3/10",
		desc: "After witnessing his parents' death, billionaire Bruce Wayne learns the art of fighting to confront injustice. When he returns to Gotham as Batman, he must stop a secret society that intends to destroy the city.",
		similar: ["Tenet", "TheBatman", "BatmanSuperman", "SuicideSquad1"],
		sequels: ["TheDarkKnight2","TheDarkKnight3"],
        poster: "movies/darkknight/darkknight1.jpg",
        link: "https://www.warnerbros.com/movies/batman-begins",
        trailer: "neY2xVmOfUM"
	},
	"TheDarkKnight3": {
		title: "The Dark Knight Rises",
		year: 2012,
		runtime: "2h 44m",
		genres: ["Action", "Drama", "Crime", "Superhero"],
		director: "Christopher Nolan",
		cast: ["Christian Bale", "Joseph Gordon-Levitt", "Anne Hathaway", "Marion Cotillard", "Michael Caine", "Morgan Freeman", "Gary Oldman"],
		franchise: "DarkKnightTrilogy",
		keywords: ["Hero", "Chaos", "Villain"],
		ageRating: "12A",
		rating: "8.3/10",
		desc: "Bane, an imposing terrorist, attacks Gotham City and disrupts its eight-year-long period of peace. This forces Bruce Wayne to come out of hiding and don the cape and cowl of Batman again.",
		similar: ["Tenet", "TheBatman", "BatmanSuperman", "SuicideSquad1"],
		sequels: ["TheDarkKnight1","TheDarkKnight2"],
        poster: "movies/darkknight/darkknight3.jpg",
        link: "https://www.warnerbros.com/movies/dark-knight-rises",
        trailer: "g8evyE9TuYk"
	},
	"TheBatman": {
		title: "The Batman",
		year: 2022,
		runtime: "2h 56m",
		genres: ["Action", "Drama", "Crime", "Superhero"],
		director: "Matt Reeves",
		cast: ["Robert Pattinson", "Zoe Kravitz", "Paul Dano", "Colin Farrell", "Jeffrey Wright", "John Turturro", "Andy Serkis"],
		franchise: null,
		keywords: ["Hero", "Chaos", "Villain"],
		ageRating: "15",
		rating: "8.1/10",
		desc: "When a sadistic serial killer begins murdering key political figures in Gotham, the Batman is forced to investigate the city's hidden corruption and question his family's involvement.",
		similar: ["TheDarkKnight1", "TheDarkKnight2", "TheDarkKnight3", "BatmanSuperman"],
		sequels: [],
        poster: "movies/thebatman/thebatman.jpg",
        link: "https://www.warnerbros.com/movies/the-batman",
        trailer: "mqqft2x_Aa4"
	},
	"BatmanSuperman": {
		title: "Batman v Superman: Dawn of Justice",
		year: 2016,
		runtime: "2h 31m",
		genres: ["Action", "Drama", "Superhero", "Sci-Fi"],
		director: "Zack Snyder",
		cast: ["Ben Affleck", "Henry Cavill", "Jesse Eisenberg", "Gal Gadot", "Jeremy Irons", "Holly Hunter"],
		franchise: null,
		keywords: ["Batman", "Superman", "Justice", "Hero", "Villain"],
		ageRating: "12A",
		rating: "7.2/10",
		desc: "Batman is manipulated by Lex Luthor to fear Superman. Superman´s existence is meanwhile dividing the world and he is framed for murder during an international crisis. The heroes clash and force the neutral Wonder Woman to reemerge.",
		similar: ["TheBatman", "TheDarkKnight1", "TheDarkKnight2", "TheDarkKnight3", "SuicideSquad1"],
		sequels: ["TheDarkKnight1","TheDarkKnight2"],
        poster: "movies/darkknight/darkknight3.jpg",
        link: "https://www.warnerbros.com/movies/batman-v-superman-dawn-justice",
        trailer: "0WWzgGyAH6Y"
	},
	"SuicideSquad1": {
		title: "Suicide Squad",
		year: 2016,
		runtime: "2h 10m",
		genres: ["Action", "Fantasy", "Drama", "Superhero", "Sci-Fi"],
		director: "James Gunn",
		cast: ["Margot Robbie", "Jared Leto", "Will Smith", "Joel Kinnaman", "Viola Davis", "Jai Courtney", "Scott Eastwood", "David Harbour", "Common"],
		franchise: "SSquad",
		keywords: ["Mission", "DC", "Team"],
		ageRating: "15",
		rating: "7.2/10",
		desc: "A secret government agency recruits some of the most dangerous incarcerated super-villains to form a defensive task force. Their first mission: save the world from the apocalypse.",
		similar: ["TheDarkKnight1","TheDarkKnight2","TheDarkKnight3","BatmanSuperman"],
		sequels: ["SuicideSquad2"],
        poster: "movies/suicidesquad/suicidesquad1.jpg",
        link: "https://www.warnerbros.com/movies/suicide-squad",
        trailer: "CmRih_VtVAs"
	},
	"SuicideSquad2": {
		title: "The Suicide Squad",
		year: 2021,
		runtime: "2h 12m",
		genres: ["Action", "Fantasy", "Drama", "Superhero", "Sci-Fi"],
		director: "James Gunn",
		cast: ["Margot Robbie", "John Cena", "Nathan Fillion", "Daniela Melchior", "Idris Elba", "Joel Kinnaman", "David Dastmalchian", "Jennifer Holland", "Peter Capaldi"],
		franchise: "SSquad",
		keywords: ["Mission", "DC", "Team"],
		ageRating: "15",
		rating: "7.3/10",
		desc: "Supervillains Harley Quinn, Bloodsport, Peacemaker, and a collection of nutty cons at Belle Reve prison join the super-secret, super-shady Task Force X as they are dropped off at the remote, enemy-infused island of Corto Maltese.",
		similar: ["TheDarkKnight1","TheDarkKnight2","TheDarkKnight3","BatmanSuperman"],
		sequels: ["SuicideSquad2"],
        poster: "movies/suicidesquad/suicidesquad2.jpg",
        link: "https://www.warnerbros.com/movies/the-suicide-squad",
        trailer: "eg5ciqQzmK0"
	},
	"ForrestGump": {
		title: "Forrest Gump",
		year: 1994,
		runtime: "2h 22m",
		genres: ["Comedy", "Adventure", "Drama"],
		director: "Robert Zemeckis",
		cast: ["Tom Hanks", "Robin Wright", "Gary Sinise", "Sally Field"],
		franchise: null,
		keywords: ["History", "War", "Idiot"],
		ageRating: "12",
		rating: "9.4/10",
		desc: "The history of the United States from the 1950s to the '70s unfolds from the perspective of an Alabama man with an IQ of 75, who yearns to be reunited with his childhood sweetheart.",
		similar: [],
		sequels: [],
        poster: "movies/forrestgump/forrestgump.jpg",
        link: "https://www.paramountmovies.com/movies/forrest-gump",
        trailer: "bLvqoHBptjg"
	},
	"Alien1": {
		title: "Alien",
		year: 1979,
		runtime: "1h 57m",
		genres: ["Horror", "Sci-Fi", "Action"],
		director: "Ridley Scott",
		cast: ["Sigourney Weaver", "Tom Skerritt", "Veronica Cartwright", "John Hurt", "Ian Holm", "Harry Dean Stanton", "Bolaji Badejo"],
		franchise: "Alien",
		keywords: ["Alien", "Space"],
		ageRating: "15",
		rating: "8.7/10",
		desc: "After investigating a mysterious transmission of unknown origin, the crew of a commercial spacecraft encounters a deadly lifeform.",
		similar: ["TheThing", "TheThing2", "Oxygen"],
		sequels: ["Alien2", "Alien3", "Alien4", "Alien5"],
        poster: "movies/alien/alien.jpg",
        link: "https://www.20thcenturystudios.com/movies/alien",
        trailer: "LjLamj-b0I8"
	},
	"Alien2": {
		title: "Aliens",
		year: 1986,
		runtime: "2h 17m",
		genres: ["Horror", "Sci-Fi", "Action"],
		director: "James Cameron",
		cast: ["Sigourney Weaver", "Carrie Henn", "Bill Paxton", "Michael Biehn", "Lance Henriksen", "Paul Reiser"],
		franchise: "Alien",
		keywords: ["Alien", "Space"],
		ageRating: "15",
		rating: "9/10",
		desc: "Decades after surviving the Nostromo incident, Ellen Ripley is sent out to re-establish contact with a terraforming colony but finds herself battling the Alien Queen and her offspring.",
		similar: ["TheThing", "TheThing2", "Oxygen"],
		sequels: ["Alien1", "Alien3", "Alien4", "Alien5"],
        poster: "movies/alien/aliens.jpg",
        link: "https://www.20thcenturystudios.com/movies/aliens",
        trailer: "XKSQmGWaQ94"
	},
	"Alien3": {
		title: "Alien 3",
		year: 1992,
		runtime: "1h 54m",
		genres: ["Horror", "Sci-Fi", "Action"],
		director: "David Fincher",
		cast: ["Sigourney Weaver", "Charles Dance", "David Giler", "Terry Rawlings", "Lance Henriksen", "Pete Postlethwaite", "Brian Glover", "Ralph Brown"],
		franchise: "Alien",
		keywords: ["Alien", "Space"],
		ageRating: "15",
		rating: "8.3/10",
		desc: "Returning from LV-426, Ellen Ripley crash-lands on the maximum-security prison Fiorina 161, where she discovers that she has unwittingly brought along an unwelcome visitor.",
		similar: ["TheThing", "TheThing2", "Oxygen"],
		sequels: ["Alien1", "Alien2", "Alien4", "Alien5"],
        poster: "movies/alien/alien3.jpg",
        link: "https://www.20thcenturystudios.com/movies/alien-3",
        trailer: "M94I16hf3j0"
	},
	"Alien4": {
		title: "Alien Resurrection",
		year: 1997,
		runtime: "1h 49m",
		genres: ["Horror", "Sci-Fi", "Action"],
		director: "Jean-Pierre Jeunet",
		cast: ["Sigourney Weaver", "Winona Ryder", "Ron Perlman", "Dominique Pinon", "Kim Flowers", "Brad Dourif", "Michael Wincott"],
		franchise: "Alien",
		keywords: ["Alien", "Space"],
		ageRating: "15",
		rating: "8.3/10",
		desc: "Two centuries after her death, a powerful human/alien hybrid clone of Ellen Ripley aids a crew of space pirates in stopping the aliens from reaching Earth.",
		similar: ["TheThing", "TheThing2", "Oxygen"],
		sequels: ["Alien1", "Alien2", "Alien3", "Alien5"],
        poster: "movies/alien/alien4.jpg",
        link: "https://www.20thcenturystudios.com/movies/alien-resurrection",
        trailer: "4Z8J_zE8xVw"
	},
	"Alien5": {
		title: "AVP: Alien vs. Predator",
		year: 2004,
		runtime: "1h 41m",
		genres: ["Horror", "Sci-Fi", "Action"],
		director: "Paul W. S. Anderson",
		cast: ["Ian Whyte", "Sanaa Lathan", "Tom Woodruff Jr.", "Lance Henriksen", "Alec Gillis", "Colin Salmon", "Ewen Bremner", "Raoul Bova"],
		franchise: "Alien",
		keywords: ["Alien", "Space"],
		ageRating: "15",
		rating: "8.1/10",
		desc: "During an archaeological expedition on Bouvetøya Island in Antarctica, a team of archaeologists and other scientists find themselves caught up in a battle between the two legends. Soon, the team realize that only one species can win.",
		similar: ["TheThing", "TheThing2", "Oxygen"],
		sequels: ["Alien1", "Alien2", "Alien3", "Alien 4"],
        poster: "movies/alien/alienvpred.jpg",
        link: "https://www.20thcenturystudios.com/movies/avp-alien-vs-predator",
        trailer: "-p7C5v9r-Yk"
	},
	"TheThing": {
		title: "The Thing",
		year: 1982,
		runtime: "1h 49m",
		genres: ["Horror", "Sci-Fi", "Suspense", "Mystery"],
		director: "John Carpenter",
		cast: ["Kurt Russell", "Keith David", "Wilford Brimley", "Richard Masur", "T. K. Carter", "David Clennon", "Donald Moffat"],
		franchise: "TheThing",
		keywords: ["Alien", "Imposter"],
		ageRating: "18",
		rating: "8.7/10",
		desc: "A research team in Antarctica is hunted by a shape-shifting alien that assumes the appearance of its victims.",
		similar: ["Alien", "Aliens", "Oxygen"],
		sequels: ["The Thing"],
        poster: "movies/thething/thething.jpg",
        link: "https://www.imdb.com/title/tt0084787/",
        trailer: "5ftmr17M-P4"
	},
	"TheThing2": {
		title: "The Thing",
		year: 2011,
		runtime: "1h 43m",
		genres: ["Horror", "Sci-Fi", "Suspense", "Mystery"],
		director: "Matthijs van Heijningen Jr.",
		cast: ["Mary Elizabeth Winstead", "Joel Edgerton", "Ulrich Thomsen", "Adewale Akinnuoye", "Kim Bubbs", "Kristofer Hivju", "Eric Christian Olsen", "Trond Espen Seim"],
		franchise: "TheThing",
		keywords: ["Alien", "Imposter"],
		ageRating: "15",
		rating: "8/10",
		desc: "A group of scientists researching an alien spaceship found in the Antarctic come face to face with the ship's, not quite dead, occupant.",
		similar: ["Oxygen"],
		sequels: ["Alien", "Aliens", "The Thing"],
        poster: "movies/thething/thething2.jpg",
        link: "https://www.imdb.com/title/tt0905372/",
        trailer: "Txjm94GnrPA"
	},
	"KPopDemonHunters": {
		title: "KPop Demon Hunters",
		year: 2025,
		runtime: "1h 39m",
		genres: ["Animation", "Musical", "Action"],
		director: "Maggie Kang",
		cast: ["Ken Jeong", "Arden Cho", "Liza Koshy", "May Hong", "SungWon Cho", "Daniel Dae Kim", "Yunjin Kim"],
		franchise: null,
		keywords: [],
		ageRating: "PG",
		rating: "8.3/10",
		desc: "A world-renowned K-Pop girl group balance their lives in the spotlight with their secret identities as demon hunters.",
		similar: [],
		sequels: [],
		poster: "movies/kpopdemonhunters/kpopdemonhunters.jpg",
		link: "https://www.imdb.com",
        trailer: "dQw4w9WgXcQ" // Generic/Placeholder
	},
	"Superman": {
		title: "Superman",
		year: 2025,
		runtime: "2h 10m",
		genres: ["Action","Sci-Fi","Superhero"],
		director: "James Gunn",
		cast: ["David Corenswet", "Rachel Brosnahan", "Nicholas Hoult", "Isabela Merced", "Milly Alcock", "Mikaela Hoover", "Nathan Fillion", "Sara Sampaio"],
		franchise: null,
		keywords: ["DC"],
		ageRating: "12A",
		rating: "8.5/10",
		desc: "A world-renowned K-Pop girl group balance their lives in the spotlight with their secret identities as demon hunters.",
		similar: ["BatmanSuperman"],
		sequels: [],
		poster: "movies/superman/superman.jpg",
		link: "https://www.imdb.com",
        trailer: "dQw4w9WgXcQ" // Generic/Placeholder
	},
	"F1": {
		title: "F1",
		year: 2025,
		runtime: "2h 35m",
		genres: ["Action", "Sport", "Adventure"],
		director: "Joseph Kosinski",
		cast: ["Brad Pitt", "Kerry Condon", "Damson Idris", "Javier Bardem", "Lewis Hamilton", "Max Verstappen", "Callie Cooke", "Lando Norris"],
		franchise: null,
		keywords: ["Racing", "Cars"],
		ageRating: "12A",
		rating: "8.9/10",
		desc: "A Formula One driver comes out of retirement to mentor and team up with a younger driver.",
		similar: [],
		sequels: [],
		poster: "movies/F1/F1.jpg",
		link: "https://www.imdb.com",
        trailer: "a27X-2849aw" // F1 Teaser
	},
	"Frankenstein": {
		title: "Frankenstein",
		year: 2025,
		runtime: "2h 29m",
		genres: ["Horror", "Sci-Fi", "Adventure", "Drama"],
		director: "Guillermo del Toro",
		cast: ["Jacob Elordi", "Mia Goth", "Oscar Isaac", "Christoph Waltz", "Felix Kammerer", "Charles Dance", "Ralph Ineson", "Sofia Galasso"],
		franchise: null,
		keywords: ["Monster", "Scientist"],
		ageRating: "15",
		rating: "9.2/10",
		desc: "Dr. Victor Frankenstein, a brilliant but egotistical scientist, brings a creature to life in a monstrous experiment that ultimately leads to the undoing of both the creator and his tragic creation.",
		similar: [],
		sequels: [],
		poster: "movies/frankenstein/frankenstein.jpg",
		link: "https://www.imdb.com",
        trailer: "dQw4w9WgXcQ" // Generic/Placeholder
	},
	"Wicked1": {
		title: "Wicked",
		year: 2024,
		runtime: "2h 40m",
		genres: ["Fantasy", "Musical", "Drama"],
		director: "Jon M. Chu",
		cast: ["Cynthia Erivo", "Ariana Grande", "Jonathan Bailey", "Ethan Slater", "Michelle Yeoh", "Marissa Bode", "Jeff Goldblum", "Peter Dinklage"],
		franchise: "Wicked",
		keywords: ["Witch", "Magical"],
		ageRating: "PG",
		rating: "7.8/10",
		desc: "Elphaba, a young woman ridiculed for her green skin, and Galinda, a popular girl, become friends at Shiz University in the Land of Oz. After an encounter with the Wonderful Wizard of Oz, their friendship reaches a crossroads.",
		similar: [],
		sequels: ["Wicked2"],
		poster: "movies/wicked/wicked.jpg",
		link: "https://www.universalpictures.com/movies/wicked",
        trailer: "F1W2t6n3aQ" // Wicked Trailer
	},
	"Wicked2": {
		title: "Wicked: For Good",
		year: 2025,
		runtime: "2h 17m",
		genres: ["Fantasy", "Musical", "Drama"],
		director: "Jon M. Chu",
		cast: ["Cynthia Erivo", "Ariana Grande", "Jonathan Bailey", "Ethan Slater", "Michelle Yeoh", "Marissa Bode", "Jeff Goldblum", "Peter Dinklage"],
		franchise: "Wicked",
		keywords: ["Witch", "Magical"],
		ageRating: "PG",
		rating: "8.6/10",
		desc: "Elphaba, the future Wicked Witch of the West and her relationship with Glinda, the Good Witch of the North. The second of a two-part feature film adaptation of the Broadway musical.",
		similar: [],
		sequels: ["Wicked1"],
		poster: "movies/wicked/wickedforgood.jpg",
		link: "https://www.imdb.com",
        trailer: "dQw4w9WgXcQ" // Generic/Placeholder
	},
	"HappyGilmore2": {
		title: "Happy Gilmore 2",
		year: 2025,
		runtime: "1h 58m",
		genres: ["Comedy", "Action"],
		director: "Kyle Newacheck",
		cast: ["Bad Bunny", "Eminem", "Travis Kelce", "Margaret Qualley", "John Daly", "Sunny Sandler", "Haley Joel Osment", "Benny Safdie"],
		franchise: null,
		keywords: ["Golf", "Satire"],
		ageRating: "12A",
		rating: "7.4/10",
		desc: "To provide for his family, a retired Happy Gilmore must pick up the golf clubs once more and reconnect with the sport he once dominated.",
		similar: [],
		sequels: ["HappyGilmore"], 
		poster: "movies/happygilmore/happygilmore2.jpg",
		link: "https://www.imdb.com",
        trailer: "dQw4w9WgXcQ" // Generic/Placeholder
	},
	"Zootropolis2": {
		title: "Zootropolis 2",
		year: 2025,
		runtime: "1h 48m",
		genres: ["Animation", "Comedy", "Adventure"],
		director: ["Jared Bush", "Byron Howard"],
		cast: ["Shakira", "Ke Huy Quan", "Macaulay Culkin", "Quinta Brunson", "Fortune Feimster", "Patrick Warburton", "Robert Irwin", "Josh Dallas"],
		franchise: "Zootropolis",
		keywords: ["Animals", "Cartoon"],
		ageRating: "PG",
		rating: "9.4/10",
		desc: "Brave rabbit cop Judy Hopps and her friend, the fox Nick Wilde, team up again to crack a new case, the most perilous and intricate of their careers.",
		similar: [],
		sequels: ["Zootropolis1"], 
		poster: "movies/zootropolis/zootropolis2.jpg",
		link: "https://www.imdb.com",
        trailer: "dQw4w9WgXcQ" // Generic/Placeholder
	},
	"TrainDreams": {
		title: "Train Dreams",
		year: 2025,
		runtime: "1h 42m",
		genres: ["Drama"],
		director: "Clint Bentley",
		cast: ["Joel Edgerton", "Felicity Jones", "Will Patton", "Kerry Condon", "William H. Macy", "John Diehl", "Paul Schneider", "Nathaniel Arcand"],
		franchise: null,
		keywords: ["Immigrant", "Grief"],
		ageRating: "12A",
		rating: "7.4/10",
		desc: "Based on Denis Johnson's beloved novella, Train Dreams is the moving portrait of Robert Grainier, a logger and railroad worker who leads a life of unexpected depth and beauty in the rapidly-changing America of the early 20th Century.",
		similar: [],
		sequels: [],
		poster: "movies/traindreams/traindreams.jpg",
		link: "https://www.imdb.com",
        trailer: "dQw4w9WgXcQ" // Generic/Placeholder
	},
	"Avatar3": {
		title: "Avatar: Fire and Ash",
		year: 2025,
		runtime: "3h 17m",
		genres: ["Action", "Fantasy", "Animation", "Adventure", "Sci-Fi"],
		director: "James Cameron",
		cast: ["Zoe Saldana", "Sam Worthington", "Sigourney Weaver", "Stephen Lang", "Oona Chaplin", "Kate Winslet", "Michelle Yeoh", "David Thewlis"],
		franchise: "Avatar",
		keywords: ["Tribes", "Grief"],
		ageRating: "12A",
		rating: "-/10",
		desc: "Jake and Neytiri's family grapples with grief after Neteyam's death, encountering a new, aggressive Na'vi tribe, the Ash People, who are led by the fiery Varang, as the conflict on Pandora escalates and a new moral focus emerges.",
		similar: [],
		sequels: ["Avatar1", "Avatar2"],
		poster: "movies/avatar/avatar3.jpg",
		link: "https://www.imdb.com",
        trailer: "dQw4w9WgXcQ" // Generic/Placeholder
	},
	"Spiderman5": {
		title: "Spider-Man: Brand New Day",
		year: 2026,
		runtime: "3h 17m",
		genres: ["Action", "Adventure", "Sci-Fi", "Superhero"],
		director: "Destin Daniel Cretton",
		cast: ["Sadie Pink", "Tom Holland", "Zendaya", "Jon Bernthal", "Michael Mando", "Jacob Batalon", "Mark Ruffalo", "Krondon"],
		franchise: "Spiderman",
		keywords: ["Marvel"],
		ageRating: "12A",
		rating: "-/10",
		desc: "Peter Parker tries to focus on college and leave Spider-Man behind. But when a new threat endangers his friends, he must break his promise and suit up again, teaming with an unexpected ally to protect those he loves.",
		similar: [],
		sequels: ["Spideman1","Spideman2","Spiderman3","Spiderman4"], 
		poster: "movies/spiderman/spidermanbrandnewday.jpg",
		link: "https://www.imdb.com",
        trailer: "dQw4w9WgXcQ" // Generic/Placeholder
	},
	"Odyssey": {
		title: "The Odyssey",
		year: 2026,
		runtime: "-h -m",
		genres: ["Action", "Fantasy", "Adventure"],
		director: "Christopher Nolan",
		cast: ["Matt Damon", "Mia Goth", "Anne Hathaway"],
		franchise: null,
		keywords: ["Trojan", "Monster", "Ocean"],
		ageRating: "12A",
		rating: "-/10",
		desc: "After the Trojan War, Odysseus faces a dangerous voyage back to Ithaca, meeting creatures like the Cyclops Polyphemus, Sirens, and Circe along the way.",
		similar: [],
		sequels: [],
		poster: "movies/theodyssey/theodyssey.jpg",
		link: "https://www.imdb.com",
        trailer: "dQw4w9WgXcQ" // Generic/Placeholder
	},
	"ToyStory5": {
		title: "Toy Story 5",
		year: 2026,
		runtime: "-h -m",
		genres: ["Animation", "Comedy", "Adventure"],
		director: "Andrew Stanton",
		cast: ["Tom Hanks", "Tim Allen", "Ernie Hudson", "Joan Cusack"],
		franchise: "ToyStory",
		keywords: ["Trojan", "Monster", "Ocean"],
		ageRating: "U",
		rating: "-/10",
		desc: "Buzz, Woody, Jessie are challenged after being introduced to what kids are obsessed with today: electronics.",
		similar: [],
		sequels: ["ToyStory1","ToyStory2","ToyStory3","ToyStory4"],
		poster: "movies/toystory/toystory5.jpg",
		link: "https://www.imdb.com",
        trailer: "dQw4w9WgXcQ" // Generic/Placeholder
	},
	"Scream7": {
		title: "Scream 7",
		year: 2026,
		runtime: "-h -m",
		genres: ["Horror", "Mystery"],
		director: "Kevin Williamson",
		cast: ["Neve Campbell", "Courtney Cox", "Isabel May", "Matthew Lillard", "Mason Gooding", "David Arquette"],
		franchise: "Scream",
		keywords: ["Slasher", "Mask"],
		ageRating: "18",
		rating: "-/10",
		desc: "When a new Ghostface killer emerges in the town where Sidney Prescott has built a new life, her darkest fears are realized as her daughter becomes the next target.",
		similar: [],
		sequels: ["Scream","Scream2","Scream3","Scream4","Scream5","Scream6"], 
		poster: "movies/scream/scream7.jpg",
		link: "https://www.imdb.com",
        trailer: "dQw4w9WgXcQ" // Generic/Placeholder
	},
	"GreenMile": {
		title: "Green Mile",
		year: 1999,
		runtime: "3h 09m",
		genres: ["Horror", "Drama", "Crime"],
		director: "Frank Darabont",
		cast: ["Michael Clarke Duncan", "Tom Hanks", "David Morse", "Sam Rockwell", "Michael Jeter", "James Cromwell", "Doug Hutchison", "Barry Pepper"],
		franchise: null,
		keywords: ["Innocence", "Justice", "Execution"],
		ageRating: "18",
		rating: "9.1/10",
		desc: "A death row guard learns that a gentle giant in his charge possesses a mysterious gift.",
		similar: [],
		sequels: [],
		poster: "movies/greenmile/greenmile.jpg",
		link: "https://www.warnerbros.com",
        trailer: "Ki4haFrq0sg"
	}
};

const exploreLists = {
    trending: [
        "KPopDemonHunters", "Superman", "F1", "Frankenstein", 
        "Wicked2", "HappyGilmore2", "Zootropolis2", "TrainDreams"
    ],
    upcoming: [
        "Avatar3", "Spiderman5", "Odyssey", "ToyStory5", "Scream7", 
        "Alien5", "HarryPotter8"
    ],
    seasonal: [	
        "HarryPotter1", "HarryPotter2", "HarryPotter3", "HarryPotter4", "HarryPotter5", 
        "ForrestGump", "TheThing"
    ]
};