const movieData = {
	"Inception": {
		title: "Inception",
		year: 2010,
		runtime: "2h 28m",
		genres: ["Action", "Sci-Fi", "Thriller"],
		director: "Christopher Nolan",
		cast: ["Leonardo DiCaprio", "Joseph Gordon-Levitt", "Elliot Page"],
		franchise: null,
		keywords: ["Dream", "Heist", "Mind-bending"],
		rating: "8.8/10",
		desc: "A skilled thief who steals secrets through dream-sharing technology is given the inverse task of planting an idea into the mind of a C.E.O.",
		similar: ["TheMatrix", "Interstellar", "Tenet"],
		sequels: [],
        poster: "movies/inception/Inception.jpg",
        link: "https://www.youtube.com/results?search_query=Inception+movie"
	},
	"TheMatrix": {
		title: "The Matrix",
		year: 1999,
		runtime: "2h 16m",
		genres: ["Action", "Sci-Fi"],
		director: "The Wachowskis",
		cast: ["Keanu Reeves", "Laurence Fishburne", "Carrie-Anne Moss"],
		franchise: "Matrix",
		keywords: ["Simulation", "Dystopian", "Kung Fu"],
		rating: "8.7/10",
		desc: "A hacker discovers the shocking truth about reality and his role in the war against its controllers.",
		similar: ["Inception", "Dark City", "Equilibrium"],
		sequels: ["TheMatrix2", "TheMatrix3", "TheMatrix4"],
        poster: "movies/matrix/The Matrix.jpg",
        link: "https://www.youtube.com/results?search_query=The+Matrix+movie"
	},
	"TheMatrix2": {
		title: "The Matrix Reloaded",
		year: 2003,
		runtime: "2h 18m",
		genres: ["Action", "Sci-Fi"],
		director: "The Wachowskis",
		cast: ["Keanu Reeves", "Laurence Fishburne", "Carrie-Anne Moss"],
		franchise: "Matrix",
		keywords: ["Simulation", "Dystopian", "Kung Fu"],
		rating: "8.6/10",
		desc: "A liberating hero races to uncover deeper layers of control, confronting new foes and revelations that challenge everything he believes about fate and freedom.",
		similar: ["Inception", "Dark City", "Equilibrium"],
		sequels: ["TheMatrix", "TheMatrix3", "TheMatrix4"],
        poster: "movies/matrix/The Matrix2.jpg",
        link: "https://www.youtube.com/results?search_query=The+Matrix+Reloaded+movie"
	},
	"TheMatrix3": {
		title: "The Matrix Revolutions",
		year: 2003,
		runtime: "2h 09m",
		genres: ["Action", "Sci-Fi"],
		director: "The Wachowskis",
		cast: ["Keanu Reeves", "Laurence Fishburne", "Carrie-Anne Moss"],
		franchise: "Matrix",
		keywords: ["Simulation", "Dystopian", "Kung Fu"],
		rating: "8.8/10",
		desc: "As the war reaches its breaking point, a chosen fighter battles on two fronts—both human and machine—to forge a final path toward peace.",
		similar: ["Inception", "Dark City", "Equilibrium"],
		sequels: ["TheMatrix", "TheMatrix2", "TheMatrix4"],
        poster: "movies/matrix/The Matrix3.jpg",
        link: "https://www.youtube.com/results?search_query=The+Matrix+Revolutions+movie"
	},
	"TheMatrix4": {
		title: "The Matrix Resurrections",
		year: 2021,
		runtime: "2h 28m",
		genres: ["Action", "Sci-Fi"],
		director: "The Wachowskis",
		cast: ["Keanu Reeves", "Laurence Fishburne", "Carrie-Anne Moss"],
		franchise: "Matrix",
		keywords: ["Simulation", "Dystopian", "Kung Fu"],
		rating: "5.9/10",
		desc: "Drawn back into a reality he once escaped, a weary legend confronts illusions, lost memories, and a renewed struggle for truth in a world more deceptive than ever.",
		similar: ["Inception", "Dark City", "Equilibrium"],
		sequels: ["TheMatrix", "TheMatrix2", "TheMatrix3"],
        poster: "movies/matrix/The Matrix4.jpg",
        link: "https://www.youtube.com/results?search_query=The+Matrix+Resurrections+movie"
	},
	"HarryPotter1": {
		title: "Harry Potter and the Philosopher's Stone",
		year: 2001,
		runtime: "2h 32m",
		genres: ["Fantasy", "Action", "Adventure"],
		director: "Chris Columbus",
		cast: ["Daniel Radcliffe", "Emma Watson", "Rupert Grint"],
		franchise: "HarryPotter",
		keywords: ["Magic", "School", "Wizards"],
		rating: "9.6/10",
		desc: "A young wizard discovers a hidden power within his school, drawing him into a perilous quest for an artifact of immortality.",
		similar: [],
		sequels: ["HarryPotter2", "HarryPotter3", "HarryPotter4", "HarryPotter5", "HarryPotter6","HarryPotter7","HarryPotter8"],
        poster: "movies/harrypotter/hp1.jpg",
        link: "https://www.youtube.com/results?search_query=Harry+Potter+and+the+Philosopher%27s+Stone+movie"
	},
	"HarryPotter2": {
		title: "Harry Potter and the Chamber of Secrets",
		year: 2002,
		runtime: "2h 38m",
		genres: ["Fantasy", "Action", "Adventure"],
		director: "Chris Columbus",
		cast: ["Daniel Radcliffe", "Emma Watson", "Rupert Grint"],
		franchise: "HarryPotter",
		keywords: ["Magic", "School", "Mystery"],
		rating: "9.4/10",
		desc: "A young wizard confronts an ancient chamber within his school, unraveling a sinister mystery bound to a dark legacy.",
		similar: [],
		sequels: ["HarryPotter1", "HarryPotter3", "HarryPotter4", "HarryPotter5", "HarryPotter6","HarryPotter7","HarryPotter8"],
        poster: "movies/harrypotter/hp2.jpg",
        link: "https://www.youtube.com/results?search_query=Harry+Potter+and+the+Chamber+of+Secrets+movie"
	},
	"HarryPotter3": {
		title: "Harry Potter and the Prisoner of Azkaban",
		year: 2004,
		runtime: "2h 22m",
		genres: ["Fantasy", "Action", "Adventure"],
		director: "Alfonso Cuarón",
		cast: ["Daniel Radcliffe", "Emma Watson", "Rupert Grint"],
		franchise: "HarryPotter",
		keywords: ["Magic", "Time Travel", "Werewolf"],
		rating: "9.6/10",
		desc: "A young wizard faces ominous omens and a fugitive’s escape, uncovering secrets that will alter his understanding of the past.",
		similar: [],
		sequels: ["HarryPotter1", "HarryPotter2", "HarryPotter4", "HarryPotter5", "HarryPotter6","HarryPotter7","HarryPotter8"],
        poster: "movies/harrypotter/hp3.jpg",
        link: "https://www.youtube.com/results?search_query=Harry+Potter+and+the+Prisoner+of+Azkaban+movie"
	},
	"HarryPotter4": {
		title: "Harry Potter and the Goblet of Fire",
		year: 2005,
		runtime: "2h 37m",
		genres: ["Fantasy", "Action", "Adventure"],
		director: "Mike Newell",
		cast: ["Daniel Radcliffe", "Emma Watson", "Rupert Grint"],
		franchise: "HarryPotter",
		keywords: ["Magic", "Tournament", "Dark Lord"],
		rating: "8.6/10",
		desc: "Thrust into a perilous tournament, a young wizard confronts deadly challenges and a dark resurgence that signals the return of an ancient threat.",
		similar: [],
		sequels: ["HarryPotter1", "HarryPotter2", "HarryPotter3", "HarryPotter5", "HarryPotter6","HarryPotter7","HarryPotter8"],
        poster: "movies/harrypotter/hp4.jpg",
        link: "https://www.youtube.com/results?search_query=Harry+Potter+and+the+Goblet+of+Fire+movie"
	},
	"HarryPotter5": {
		title: "Harry Potter and the Order of the Phoenix",
		year: 2007,
		runtime: "2h 18m",
		genres: ["Fantasy", "Action", "Adventure"],
		director: "David Yates",
		cast: ["Daniel Radcliffe", "Emma Watson", "Rupert Grint"],
		franchise: "HarryPotter",
		keywords: ["Magic", "Rebellion", "Prophecy"],
		rating: "8.7/10",
		desc: "Haunted by visions and disbelief, a young wizard rallies allies against hidden tyranny as a shadowy power tightens its grip on the wizarding world.",
		similar: [],
		sequels: ["HarryPotter1", "HarryPotter2", "HarryPotter3", "HarryPotter4","HarryPotter6","HarryPotter7","HarryPotter8"],
        poster: "movies/harrypotter/hp5.jpg",
        link: "https://www.youtube.com/results?search_query=Harry+Potter+and+the+Order+of+the+Phoenix+movie"
	},
	"HarryPotter6": {
		title: "Harry Potter and the Half-Blood Prince",
		year: 2009,
		runtime: "2h 33m",
		genres: ["Fantasy", "Action", "Adventure"],
		director: "David Yates",
		cast: ["Daniel Radcliffe", "Emma Watson", "Rupert Grint"],
		franchise: "HarryPotter",
		keywords: ["Magic", "Romance", "Horcruxes"],
		rating: "8.7/10",
		desc: "As darkness spreads beyond the shadows, a young wizard delves into a mysterious textbook and buried memories, uncovering a path that leads ever closer to a rising evil’s true power.",
		similar: [],
		sequels: ["HarryPotter1", "HarryPotter2", "HarryPotter3", "HarryPotter4","HarryPotter5","HarryPotter7","HarryPotter8"],
		poster: "movies/harrypotter/hp6.jpg",
        link: "https://www.youtube.com/results?search_query=Harry+Potter+and+the+Half-Blood+Prince+movie"
	},
	"HarryPotter7": {
		title: "Harry Potter and the Deathly Hallows: Part 1",
		year: 2010,
		runtime: "2h 26m",
		genres: ["Fantasy", "Action", "Adventure"],
		director: "David Yates",
		cast: ["Daniel Radcliffe", "Emma Watson", "Rupert Grint"],
		franchise: "HarryPotter",
		keywords: ["Magic", "Journey", "War"],
		rating: "8.5/10",
		desc: "On the run from a tightening regime, three young wizards hunt for elusive relics, confronting betrayal, sacrifice, and the looming dread of a world slipping into darkness.",
		similar: [],
		sequels: ["HarryPotter1", "HarryPotter2", "HarryPotter3", "HarryPotter4","HarryPotter5","HarryPotter6","HarryPotter8"],
		poster: "movies/harrypotter/hp7.jpg",
        link: "https://www.youtube.com/results?search_query=Harry+Potter+and+the+Deathly+Hallows+Part+1+movie"
	},
	"HarryPotter8": {
		title: "Harry Potter and the Deathly Hallows: Part 2",
		year: 2011,
		runtime: "2h 10m",
		genres: ["Fantasy", "Action", "Adventure"],
		director: "David Yates",
		cast: ["Daniel Radcliffe", "Emma Watson", "Rupert Grint"],
		franchise: "HarryPotter",
		keywords: ["Magic", "Battle", "Finale"],
		rating: "8.5/10",
		desc: "In a final clash between hope and tyranny, a young wizard returns to where it all began, facing destiny, loss, and the ultimate battle that will decide the fate of the wizarding world.",
		similar: [],
		sequels: ["HarryPotter1", "HarryPotter2", "HarryPotter3", "HarryPotter4","HarryPotter5","HarryPotter6","HarryPotter7"],
		poster: "movies/harrypotter/hp8.jpg",
        link: "https://www.youtube.com/results?search_query=Harry+Potter+and+the+Deathly+Hallows+Part+2+movie"
	},
	"Interstellar": {
		title: "Interstellar",
		year: 2014,
		runtime: "2h 49m",
		genres: ["Thriller", "Sci-Fi", "Adventure"],
		director: "Christopher Nolan",
		cast: ["Matthew McConaughey", "Jessica Chastain", "Anne Hathaway", "Mackenzie Foy", "Matt Damon", "Michael Caine"],
		franchise: null,
		keywords: ["Space", "Black Hole", "Time"],
		rating: "9.2/10",
		desc: "When Earth becomes uninhabitable in the future, a farmer and ex-NASA pilot, Joseph Cooper, is tasked to pilot a spacecraft, along with a team of researchers, to find a new planet for humans.",
		similar: ["Inception", "Tenet"],
		sequels: [],
        poster: "movies/interstellar/Interstellar.jpg",
        link: "https://www.youtube.com/results?search_query=Interstellar+movie"
	},
	"Tenet": {
		title: "Tenet",
		year: 2020,
		runtime: "2h 30m",
		genres: ["Action", "Sci-Fi", "Thriller"],
		director: "Christopher Nolan",
		cast: ["John David Washington", "Robert Pattinson", "Elizabeth Debicki"],
		franchise: null,
		keywords: ["Time", "Espionage", "Entropy"],
		rating: "7.2/10",
		desc: "Armed with only one word, Tenet, and fighting for the survival of the entire world, a Protagonist journeys through a twilight world of international espionage on a mission that will unfold in something beyond real time.",
		similar: ["Inception", "Interstellar", "TheMatrix"],
		sequels: [],
        poster: "movies/tenet/Tenet.jpg",
        link: "https://www.youtube.com/results?search_query=Tenet+movie"
	},
	"TheDarkKnight2": {
		title: "The Dark Knight",
		year: 2008,
		runtime: "2h 32m",
		genres: ["Action", "Drama", "Crime", "Superhero"],
		director: "Christopher Nolan",
		cast: ["Christian Bale", "Heath Ledger", "Gary Oldman", "Aaron Eckhart", "Michael Caine", "Morgan Freeman"],
		franchise: "DarkKnightTrilogy",
		keywords: ["Hero", "Chaos", "Villain"],
		rating: "9.2/10",
		desc: "When a menace known as the Joker wreaks havoc and chaos on the people of Gotham, Batman, James Gordon and Harvey Dent must work together to put an end to the madness.",
		similar: ["Tenet", "TheBatman", "BatmanSuperman", "SuicideSquad1"],
		sequels: ["TheDarkKnight1","TheDarkKnight3"],
        poster: "movies/darkknight/darkknight2.jpg",
        link: "https://www.youtube.com/results?search_query=The+Dark+Knight+movie"
	},
	"TheDarkKnight1": {
		title: "Batman Begins",
		year: 2005,
		runtime: "2h 20m",
		genres: ["Action", "Drama", "Crime", "Superhero"],
		director: "Christopher Nolan",
		cast: ["Christian Bale", "Katie Holmes", "Cillian Murphy", "Liam Neeson", "Michael Caine", "Morgan Freeman"],
		franchise: "DarkKnightTrilogy",
		keywords: ["Hero", "Chaos", "Villain"],
		rating: "8.3/10",
		desc: "After witnessing his parents' death, billionaire Bruce Wayne learns the art of fighting to confront injustice. When he returns to Gotham as Batman, he must stop a secret society that intends to destroy the city.",
		similar: ["Tenet", "TheBatman", "BatmanSuperman", "SuicideSquad1"],
		sequels: ["TheDarkKnight2","TheDarkKnight3"],
        poster: "movies/darkknight/darkknight1.jpg",
        link: "https://www.youtube.com/results?search_query=Batman+Begins+movie"
	},
	"TheDarkKnight3": {
		title: "The Dark Knight Rises",
		year: 2012,
		runtime: "2h 44m",
		genres: ["Action", "Drama", "Crime", "Superhero"],
		director: "Christopher Nolan",
		cast: ["Christian Bale", "Joseph Gordon-Levitt", "Anne Hathaway", "Marion Cotillard", "Michael Caine", "Morgan Freeman", "Gary Oldman"],
		franchise: "DarkKnightTrilogy",
		keywords: ["Hero", "Chaos", "Villain"],
		rating: "8.3/10",
		desc: "Bane, an imposing terrorist, attacks Gotham City and disrupts its eight-year-long period of peace. This forces Bruce Wayne to come out of hiding and don the cape and cowl of Batman again.",
		similar: ["Tenet", "TheBatman", "BatmanSuperman", "SuicideSquad1"],
		sequels: ["TheDarkKnight1","TheDarkKnight2"],
        poster: "movies/darkknight/darkknight3.jpg",
        link: "https://www.youtube.com/results?search_query=The+Dark+Knight+Rises+movie"
	},
	"TheBatman": {
		title: "The Batman",
		year: 2022,
		runtime: "2h 56m",
		genres: ["Action", "Drama", "Crime", "Superhero"],
		director: "Matt Reeves",
		cast: ["Robert Pattinson", "Zoe Kravitz", "Paul Dano", "Colin Farrell", "Jeffrey Wright", "John Turturro", "Andy Serkis"],
		franchise: null,
		keywords: ["Hero", "Chaos", "Villain"],
		rating: "8.1/10",
		desc: "When a sadistic serial killer begins murdering key political figures in Gotham, the Batman is forced to investigate the city's hidden corruption and question his family's involvement.",
		similar: ["TheDarkKnight1", "TheDarkKnight2", "TheDarkKnight3", "BatmanSuperman"],
		sequels: [],
        poster: "movies/thebatman/thebatman.jpg",
        link: "https://www.youtube.com/results?search_query=The+Batman+movie"
	},
	"BatmanSuperman": {
		title: "Batman v Superman: Dawn of Justice",
		year: 2016,
		runtime: "2h 31m",
		genres: ["Action", "Drama", "Superhero", "Sci-Fi"],
		director: "Zack Snyder",
		cast: ["Ben Affleck", "Henry Cavill", "Jesse Eisenberg", "Gal Gadot", "Jeremy Irons", "Holly Hunter"],
		franchise: null,
		keywords: ["Batman", "Superman", "Justice", "Hero", "Villain"],
		rating: "7.2/10",
		desc: "Batman is manipulated by Lex Luthor to fear Superman. Superman´s existence is meanwhile dividing the world and he is framed for murder during an international crisis. The heroes clash and force the neutral Wonder Woman to reemerge.",
		similar: ["TheBatman", "TheDarkKnight1", "TheDarkKnight2", "TheDarkKnight3", "SuicideSquad1"],
		sequels: ["TheDarkKnight1","TheDarkKnight2"],
        poster: "movies/darkknight/darkknight3.jpg",
        link: "https://www.youtube.com/results?search_query=Batman+v+Superman+movie"
	},
	"SuicideSquad1": {
		title: "Suicide Squad",
		year: 2016,
		runtime: "2h 10m",
		genres: ["Action", "Fantasy", "Drama", "Superhero", "Sci-Fi"],
		director: "James Gunn",
		cast: ["Margot Robbie", "Jared Leto", "Will Smith", "Joel Kinnaman", "Viola Davis", "Jai Courtney", "Scott Eastwood", "David Harbour", "Common"],
		franchise: "SSquad",
		keywords: ["Mission", "DC", "Team"],
		rating: "7.2/10",
		desc: "A secret government agency recruits some of the most dangerous incarcerated super-villains to form a defensive task force. Their first mission: save the world from the apocalypse.",
		similar: ["TheDarkKnight1","TheDarkKnight2","TheDarkKnight3","BatmanSuperman"],
		sequels: ["SuicideSquad2"],
        poster: "movies/suicidesquad/suicidesquad1.jpg",
        link: "https://www.youtube.com/results?search_query=Suicide+Squad+2016+movie"
	},
	"SuicideSquad2": {
		title: "The Suicide Squad",
		year: 2021,
		runtime: "2h 12m",
		genres: ["Action", "Fantasy", "Drama", "Superhero", "Sci-Fi"],
		director: "James Gunn",
		cast: ["Margot Robbie", "John Cena", "Nathan Fillion", "Daniela Melchior", "Idris Elba", "Joel Kinnaman", "David Dastmalchian", "Jennifer Holland", "Peter Capaldi"],
		franchise: "SSquad",
		keywords: ["Mission", "DC", "Team"],
		rating: "7.3/10",
		desc: "Supervillains Harley Quinn, Bloodsport, Peacemaker, and a collection of nutty cons at Belle Reve prison join the super-secret, super-shady Task Force X as they are dropped off at the remote, enemy-infused island of Corto Maltese.",
		similar: ["TheDarkKnight1","TheDarkKnight2","TheDarkKnight3","BatmanSuperman"],
		sequels: ["SuicideSquad2"],
        poster: "movies/suicidesquad/suicidesquad2.jpg",
        link: "https://www.youtube.com/results?search_query=The+Suicide+Squad+2021+movie"
	},
	"ForrestGump": {
		title: "Forrest Gump",
		year: 1994,
		runtime: "2h 22m",
		genres: ["Comedy", "Adventure", "Drama"],
		director: "Robert Zemeckis",
		cast: ["Tom Hanks", "Robin Wright", "Gary Sinise", "Sally Field"],
		franchise: null,
		keywords: ["History", "War", "Idiot"],
		rating: "9.4/10",
		desc: "The history of the United States from the 1950s to the '70s unfolds from the perspective of an Alabama man with an IQ of 75, who yearns to be reunited with his childhood sweetheart.",
		similar: [],
		sequels: [],
        poster: "movies/forrestgump/forrestgump.jpg",
        link: "https://www.youtube.com/results?search_query=Forrest+Gump+movie"
	},
	"Alien1": {
		title: "Alien",
		year: 1979,
		runtime: "1h 57m",
		genres: ["Horror", "Sci-Fi", "Action"],
		director: "Ridley Scott",
		cast: ["Sigourney Weaver", "Tom Skerritt", "Veronica Cartwright", "John Hurt", "Ian Holm", "Harry Dean Stanton", "Bolaji Badejo"],
		franchise: "Alien",
		keywords: ["Alien", "Space"],
		rating: "8.7/10",
		desc: "After investigating a mysterious transmission of unknown origin, the crew of a commercial spacecraft encounters a deadly lifeform.",
		similar: ["TheThing", "TheThing2", "Oxygen"],
		sequels: ["Alien2", "Alien3", "Alien4", "Alien5"],
        poster: "movies/alien/alien.jpg",
        link: "https://www.youtube.com/results?search_query=Alien+1979+movie"
	},
	"Alien2": {
		title: "Aliens",
		year: 1986,
		runtime: "2h 17m",
		genres: ["Horror", "Sci-Fi", "Action"],
		director: "James Cameron",
		cast: ["Sigourney Weaver", "Carrie Henn", "Bill Paxton", "Michael Biehn", "Lance Henriksen", "Paul Reiser"],
		franchise: "Alien",
		keywords: ["Alien", "Space"],
		rating: "9/10",
		desc: "Decades after surviving the Nostromo incident, Ellen Ripley is sent out to re-establish contact with a terraforming colony but finds herself battling the Alien Queen and her offspring.",
		similar: ["TheThing", "TheThing2", "Oxygen"],
		sequels: ["Alien1", "Alien3", "Alien4", "Alien5"],
        poster: "movies/alien/aliens.jpg",
        link: "https://www.youtube.com/results?search_query=Aliens+movie"
	},
	"Alien3": {
		title: "Alien 3",
		year: 1992,
		runtime: "1h 54m",
		genres: ["Horror", "Sci-Fi", "Action"],
		director: "David Fincher",
		cast: ["Sigourney Weaver", "Charles Dance", "David Giler", "Terry Rawlings", "Lance Henriksen", "Pete Postlethwaite", "Brian Glover", "Ralph Brown"],
		franchise: "Alien",
		keywords: ["Alien", "Space"],
		rating: "8.3/10",
		desc: "Returning from LV-426, Ellen Ripley crash-lands on the maximum-security prison Fiorina 161, where she discovers that she has unwittingly brought along an unwelcome visitor.",
		similar: ["TheThing", "TheThing2", "Oxygen"],
		sequels: ["Alien1", "Alien2", "Alien4", "Alien5"],
        poster: "movies/alien/alien3.jpg",
        link: "https://www.youtube.com/results?search_query=Alien+3+movie"
	},
	"Alien4": {
		title: "Alien Resurrection",
		year: 1997,
		runtime: "1h 49m",
		genres: ["Horror", "Sci-Fi", "Action"],
		director: "Jean-Pierre Jeunet",
		cast: ["Sigourney Weaver", "Winona Ryder", "Ron Perlman", "Dominique Pinon", "Kim Flowers", "Brad Dourif", "Michael Wincott"],
		franchise: "Alien",
		keywords: ["Alien", "Space"],
		rating: "8.3/10",
		desc: "Two centuries after her death, a powerful human/alien hybrid clone of Ellen Ripley aids a crew of space pirates in stopping the aliens from reaching Earth.",
		similar: ["TheThing", "TheThing2", "Oxygen"],
		sequels: ["Alien1", "Alien2", "Alien3", "Alien5"],
        poster: "movies/alien/alien4.jpg",
        link: "https://www.youtube.com/results?search_query=Alien+Resurrection+movie"
	},
	"Alien5": {
		title: "AVP: Alien vs. Predator",
		year: 2004,
		runtime: "1h 41m",
		genres: ["Horror", "Sci-Fi", "Action"],
		director: "Paul W. S. Anderson",
		cast: ["Ian Whyte", "Sanaa Lathan", "Tom Woodruff Jr.", "Lance Henriksen", "Alec Gillis", "Colin Salmon", "Ewen Bremner", "Raoul Bova"],
		franchise: "Alien",
		keywords: ["Alien", "Space"],
		rating: "8.1/10",
		desc: "During an archaeological expedition on Bouvetøya Island in Antarctica, a team of archaeologists and other scientists find themselves caught up in a battle between the two legends. Soon, the team realize that only one species can win.",
		similar: ["TheThing", "TheThing2", "Oxygen"],
		sequels: ["Alien1", "Alien2", "Alien3", "Alien 4"],
        poster: "movies/alien/alienvpred.jpg",
        link: "https://www.youtube.com/results?search_query=Alien+vs+Predator+movie"
	},
	"TheThing": {
		title: "The Thing",
		year: 1982,
		runtime: "1h 49m",
		genres: ["Horror", "Sci-Fi", "Suspense", "Mystery"],
		director: "John Carpenter",
		cast: ["Kurt Russell", "Keith David", "Wilford Brimley", "Richard Masur", "T. K. Carter", "David Clennon", "Donald Moffat"],
		franchise: "TheThing",
		keywords: ["Alien", "Imposter"],
		rating: "8.7/10",
		desc: "A research team in Antarctica is hunted by a shape-shifting alien that assumes the appearance of its victims.",
		similar: ["Alien", "Aliens", "Oxygen"],
		sequels: ["The Thing"],
        poster: "movies/thething/thething.jpg",
        link: "https://www.youtube.com/results?search_query=The+Thing+1982+movie"
	},
	"TheThing2": {
		title: "The Thing",
		year: 2011,
		runtime: "1h 43m",
		genres: ["Horror", "Sci-Fi", "Suspense", "Mystery"],
		director: "Matthijs van Heijningen Jr.",
		cast: ["Mary Elizabeth Winstead", "Joel Edgerton", "Ulrich Thomsen", "Adewale Akinnuoye", "Kim Bubbs", "Kristofer Hivju", "Eric Christian Olsen", "Trond Espen Seim"],
		franchise: "TheThing",
		keywords: ["Alien", "Imposter"],
		rating: "8/10",
		desc: "A group of scientists researching an alien spaceship found in the Antarctic come face to face with the ship's, not quite dead, occupant.",
		similar: ["Oxygen"],
		sequels: ["Alien", "Aliens", "The Thing"],
        poster: "movies/thething/thething2.jpg",
        link: "https://www.youtube.com/results?search_query=The+Thing+2011+movie"
	}
};

const exploreLists = {
    trending: [
        "Inception", "TheMatrix", "HarryPotter1", "TheDarkKnight2", "SuicideSquad2", 
        "Tenet", "Alien1", "ForrestGump", "TheBatman"
    ],
    upcoming: [
        "TheBatman", "SuicideSquad2", "TheMatrix4", "TheThing2", "Tenet", 
        "Alien5", "HarryPotter8"
    ],
    seasonal: [
        "HarryPotter1", "HarryPotter2", "HarryPotter3", "HarryPotter4", "HarryPotter5", 
        "ForrestGump", "TheThing"
    ]
};