const movieData = {
	"Inception": {
		title: "Inception",
		year: 2010,
		runtime: "2h 28m",
		genres: ["Action", "Sci-Fi", "Thriller"],
		director: "Christopher Nolan",
		cast: ["Leonardo DiCaprio", "Joseph Gordon-Levitt", "Elliot Page"],
		franchise: null,
		keywords: ["Dream", "Heist", "Mind-bending"],
		ageRating: "12A",
		rating: "8.8/10",
		desc: "A skilled thief who steals secrets through dream-sharing technology is given the inverse task of planting an idea into the mind of a C.E.O.",
		similar: ["TheMatrix", "Interstellar", "Tenet"],
		sequels: [],
        poster: "movies/inception/Inception.jpg",
        link: "https://www.warnerbros.com/movies/inception",
        trailer: "YoHD9XEInc0" // Inception Trailer
	},
	"TheMatrix": {
		title: "The Matrix",
		year: 1999,
		runtime: "2h 16m",
		genres: ["Action", "Sci-Fi"],
		director: "The Wachowskis",
		cast: ["Keanu Reeves", "Laurence Fishburne", "Carrie-Anne Moss"],
		franchise: "Matrix",
		keywords: ["Simulation", "Dystopian", "Kung Fu"],
		ageRating: "15",
		rating: "8.7/10",
		desc: "A hacker discovers the shocking truth about reality and his role in the war against its controllers.",
		similar: ["Inception", "Dark City", "Equilibrium"],
		sequels: ["TheMatrix2", "TheMatrix3", "TheMatrix4"],
        poster: "movies/matrix/The Matrix.jpg",
        link: "https://www.warnerbros.com/movies/matrix",
        trailer: "vKQi3bBA1y8" // Matrix Trailer
	},
	"TheMatrix2": {
		title: "The Matrix Reloaded",
		year: 2003,
		runtime: "2h 18m",
		genres: ["Action", "Sci-Fi"],
		director: "The Wachowskis",
		cast: ["Keanu Reeves", "Laurence Fishburne", "Carrie-Anne Moss"],
		franchise: "Matrix",
		keywords: ["Simulation", "Dystopian", "Kung Fu"],
		ageRating: "15",
		rating: "8.6/10",
		desc: "A liberating hero races to uncover deeper layers of control, confronting new foes and revelations that challenge everything he believes about fate and freedom.",
		similar: ["Inception", "Dark City", "Equilibrium"],
		sequels: ["TheMatrix", "TheMatrix3", "TheMatrix4"],
        poster: "movies/matrix/The Matrix2.jpg",
        link: "https://www.warnerbros.com/movies/matrix-reloaded",
        trailer: "kYzz0FSgpSU"
	},
	"TheMatrix3": {
		title: "The Matrix Revolutions",
		year: 2003,
		runtime: "2h 09m",
		genres: ["Action", "Sci-Fi"],
		director: "The Wachowskis",
		cast: ["Keanu Reeves", "Laurence Fishburne", "Carrie-Anne Moss"],
		franchise: "Matrix",
		keywords: ["Simulation", "Dystopian", "Kung Fu"],
		ageRating: "15",
		rating: "8.8/10",
		desc: "As the war reaches its breaking point, a chosen fighter battles on two fronts—both human and machine—to forge a final path toward peace.",
		similar: ["Inception", "Dark City", "Equilibrium"],
		sequels: ["TheMatrix", "TheMatrix2", "TheMatrix4"],
        poster: "movies/matrix/The Matrix3.jpg",
        link: "https://www.warnerbros.com/movies/matrix-revolutions",
        trailer: "hMbexEPAOQI"
	},
	"TheMatrix4": {
		title: "The Matrix Resurrections",
		year: 2021,
		runtime: "2h 28m",
		genres: ["Action", "Sci-Fi"],
		director: "The Wachowskis",
		cast: ["Keanu Reeves", "Laurence Fishburne", "Carrie-Anne Moss"],
		franchise: "Matrix",
		keywords: ["Simulation", "Dystopian", "Kung Fu"],
		ageRating: "15",
		rating: "5.9/10",
		desc: "Drawn back into a reality he once escaped, a weary legend confronts illusions, lost memories, and a renewed struggle for truth in a world more deceptive than ever.",
		similar: ["Inception", "Dark City", "Equilibrium"],
		sequels: ["TheMatrix", "TheMatrix2", "TheMatrix3"],
        poster: "movies/matrix/The Matrix4.jpg",
        link: "https://www.warnerbros.com/movies/matrix-resurrections",
        trailer: "9ix7TUGnRIo"
	},
	"HarryPotter1": {
		title: "Harry Potter and the Philosopher's Stone",
		year: 2001,
		runtime: "2h 32m",
		genres: ["Fantasy", "Action", "Adventure"],
		director: "Chris Columbus",
		cast: ["Daniel Radcliffe", "Emma Watson", "Rupert Grint"],
		franchise: "HarryPotter",
		keywords: ["Magic", "School", "Wizards"],
		ageRating: "PG",
		rating: "9.6/10",
		desc: "A young wizard discovers a hidden power within his school, drawing him into a perilous quest for an artifact of immortality.",
		similar: [],
		sequels: ["HarryPotter2", "HarryPotter3", "HarryPotter4", "HarryPotter5", "HarryPotter6","HarryPotter7","HarryPotter8"],
        poster: "movies/harrypotter/hp1.jpg",
        link: "https://www.wizardingworld.com",
        trailer: "VyHV0BR_toI"
	},
	"HarryPotter2": {
		title: "Harry Potter and the Chamber of Secrets",
		year: 2002,
		runtime: "2h 38m",
		genres: ["Fantasy", "Action", "Adventure"],
		director: "Chris Columbus",
		cast: ["Daniel Radcliffe", "Emma Watson", "Rupert Grint"],
		franchise: "HarryPotter",
		keywords: ["Magic", "School", "Mystery"],
		ageRating: "PG",
		rating: "9.4/10",
		desc: "A young wizard confronts an ancient chamber within his school, unraveling a sinister mystery bound to a dark legacy.",
		similar: [],
		sequels: ["HarryPotter1", "HarryPotter3", "HarryPotter4", "HarryPotter5", "HarryPotter6","HarryPotter7","HarryPotter8"],
        poster: "movies/harrypotter/hp2.jpg",
        link: "https://www.wizardingworld.com",
        trailer: "1bq0qff4iF8"
	},
	"HarryPotter3": {
		title: "Harry Potter and the Prisoner of Azkaban",
		year: 2004,
		runtime: "2h 22m",
		genres: ["Fantasy", "Action", "Adventure"],
		director: "Alfonso Cuarón",
		cast: ["Daniel Radcliffe", "Emma Watson", "Rupert Grint"],
		franchise: "HarryPotter",
		keywords: ["Magic", "Time Travel", "Werewolf"],
		ageRating: "PG",
		rating: "9.6/10",
		desc: "A young wizard faces ominous omens and a fugitive’s escape, uncovering secrets that will alter his understanding of the past.",
		similar: [],
		sequels: ["HarryPotter1", "HarryPotter2", "HarryPotter4", "HarryPotter5", "HarryPotter6","HarryPotter7","HarryPotter8"],
        poster: "movies/harrypotter/hp3.jpg",
        link: "https://www.wizardingworld.com",
        trailer: "lAxgztbYDbs"
	},
	"HarryPotter4": {
		title: "Harry Potter and the Goblet of Fire",
		year: 2005,
		runtime: "2h 37m",
		genres: ["Fantasy", "Action", "Adventure"],
		director: "Mike Newell",
		cast: ["Daniel Radcliffe", "Emma Watson", "Rupert Grint"],
		franchise: "HarryPotter",
		keywords: ["Magic", "Tournament", "Dark Lord"],
		ageRating: "12A",
		rating: "8.6/10",
		desc: "Thrust into a perilous tournament, a young wizard confronts deadly challenges and a dark resurgence that signals the return of an ancient threat.",
		similar: [],
		sequels: ["HarryPotter1", "HarryPotter2", "HarryPotter3", "HarryPotter5", "HarryPotter6","HarryPotter7","HarryPotter8"],
        poster: "movies/harrypotter/hp4.jpg",
        link: "https://www.wizardingworld.com",
        trailer: "3EGojp4Hh6I"
	},
	"HarryPotter5": {
		title: "Harry Potter and the Order of the Phoenix",
		year: 2007,
		runtime: "2h 18m",
		genres: ["Fantasy", "Action", "Adventure"],
		director: "David Yates",
		cast: ["Daniel Radcliffe", "Emma Watson", "Rupert Grint"],
		franchise: "HarryPotter",
		keywords: ["Magic", "Rebellion", "Prophecy"],
		ageRating: "12A",
		rating: "8.7/10",
		desc: "Haunted by visions and disbelief, a young wizard rallies allies against hidden tyranny as a shadowy power tightens its grip on the wizarding world.",
		similar: [],
		sequels: ["HarryPotter1", "HarryPotter2", "HarryPotter3", "HarryPotter4","HarryPotter6","HarryPotter7","HarryPotter8"],
        poster: "movies/harrypotter/hp5.jpg",
        link: "https://www.wizardingworld.com",
        trailer: "y6ZW7KXaXYk"
	},
	"HarryPotter6": {
		title: "Harry Potter and the Half-Blood Prince",
		year: 2009,
		runtime: "2h 33m",
		genres: ["Fantasy", "Action", "Adventure"],
		director: "David Yates",
		cast: ["Daniel Radcliffe", "Emma Watson", "Rupert Grint"],
		franchise: "HarryPotter",
		keywords: ["Magic", "Romance", "Horcruxes"],
		ageRating: "12A",
		rating: "8.7/10",
		desc: "As darkness spreads beyond the shadows, a young wizard delves into a mysterious textbook and buried memories, uncovering a path that leads ever closer to a rising evil’s true power.",
		similar: [],
		sequels: ["HarryPotter1", "HarryPotter2", "HarryPotter3", "HarryPotter4","HarryPotter5","HarryPotter7","HarryPotter8"],
		poster: "movies/harrypotter/hp6.jpg",
        link: "https://www.wizardingworld.com",
        trailer: "JYLdTuL9Wjw"
	},
	"HarryPotter7": {
		title: "Harry Potter and the Deathly Hallows: Part 1",
		year: 2010,
		runtime: "2h 26m",
		genres: ["Fantasy", "Action", "Adventure"],
		director: "David Yates",
		cast: ["Daniel Radcliffe", "Emma Watson", "Rupert Grint"],
		franchise: "HarryPotter",
		keywords: ["Magic", "Journey", "War"],
		ageRating: "12A",
		rating: "8.5/10",
		desc: "On the run from a tightening regime, three young wizards hunt for elusive relics, confronting betrayal, sacrifice, and the looming dread of a world slipping into darkness.",
		similar: [],
		sequels: ["HarryPotter1", "HarryPotter2", "HarryPotter3", "HarryPotter4","HarryPotter5","HarryPotter6","HarryPotter8"],
		poster: "movies/harrypotter/hp7.jpg",
        link: "https://www.wizardingworld.com",
        trailer: "MxqsmsA8y5k"
	},
	"HarryPotter8": {
		title: "Harry Potter and the Deathly Hallows: Part 2",
		year: 2011,
		runtime: "2h 10m",
		genres: ["Fantasy", "Action", "Adventure"],
		director: "David Yates",
		cast: ["Daniel Radcliffe", "Emma Watson", "Rupert Grint"],
		franchise: "HarryPotter",
		keywords: ["Magic", "Battle", "Finale"],
		ageRating: "12A",
		rating: "8.5/10",
		desc: "In a final clash between hope and tyranny, a young wizard returns to where it all began, facing destiny, loss, and the ultimate battle that will decide the fate of the wizarding world.",
		similar: [],
		sequels: ["HarryPotter1", "HarryPotter2", "HarryPotter3", "HarryPotter4","HarryPotter5","HarryPotter6","HarryPotter7"],
		poster: "movies/harrypotter/hp8.jpg",
        link: "https://www.wizardingworld.com",
        trailer: "mObK5XD8udk"
	},
	"Interstellar": {
		title: "Interstellar",
		year: 2014,
		runtime: "2h 49m",
		genres: ["Thriller", "Sci-Fi", "Adventure"],
		director: "Christopher Nolan",
		cast: ["Matthew McConaughey", "Jessica Chastain", "Anne Hathaway", "Mackenzie Foy", "Matt Damon", "Michael Caine"],
		franchise: null,
		keywords: ["Space", "Black Hole", "Time"],
		ageRating: "12A",
		rating: "9.2/10",
		desc: "When Earth becomes uninhabitable in the future, a farmer and ex-NASA pilot, Joseph Cooper, is tasked to pilot a spacecraft, along with a team of researchers, to find a new planet for humans.",
		similar: ["Inception", "Tenet"],
		sequels: [],
        poster: "movies/interstellar/Interstellar.jpg",
        link: "https://www.paramountmovies.com/movies/interstellar",
        trailer: "zSWdZVtXT7E"
	},
	"Tenet": {
		title: "Tenet",
		year: 2020,
		runtime: "2h 30m",
		genres: ["Action", "Sci-Fi", "Thriller"],
		director: "Christopher Nolan",
		cast: ["John David Washington", "Robert Pattinson", "Elizabeth Debicki"],
		franchise: null,
		keywords: ["Time", "Espionage", "Entropy"],
		ageRating: "12A",
		rating: "7.2/10",
		desc: "Armed with only one word, Tenet, and fighting for the survival of the entire world, a Protagonist journeys through a twilight world of international espionage on a mission that will unfold in something beyond real time.",
		similar: ["Inception", "Interstellar", "TheMatrix"],
		sequels: [],
        poster: "movies/tenet/Tenet.jpg",
        link: "https://www.warnerbros.com/movies/tenet",
        trailer: "LdOM0x0XDMo"
	},
	"TheDarkKnight2": {
		title: "The Dark Knight",
		year: 2008,
		runtime: "2h 32m",
		genres: ["Action", "Drama", "Crime", "Superhero"],
		director: "Christopher Nolan",
		cast: ["Christian Bale", "Heath Ledger", "Gary Oldman", "Aaron Eckhart", "Michael Caine", "Morgan Freeman"],
		franchise: "DarkKnightTrilogy",
		keywords: ["Hero", "Chaos", "Villain"],
		ageRating: "12A",
		rating: "9.2/10",
		desc: "When a menace known as the Joker wreaks havoc and chaos on the people of Gotham, Batman, James Gordon and Harvey Dent must work together to put an end to the madness.",
		similar: ["Tenet", "TheBatman", "BatmanSuperman", "SuicideSquad1"],
		sequels: ["TheDarkKnight1","TheDarkKnight3"],
        poster: "movies/darkknight/darkknight2.jpg",
        link: "https://www.warnerbros.com/movies/dark-knight",
        trailer: "EXeTwQWrcwY"
	},
	"TheDarkKnight1": {
		title: "Batman Begins",
		year: 2005,
		runtime: "2h 20m",
		genres: ["Action", "Drama", "Crime", "Superhero"],
		director: "Christopher Nolan",
		cast: ["Christian Bale", "Katie Holmes", "Cillian Murphy", "Liam Neeson", "Michael Caine", "Morgan Freeman"],
		franchise: "DarkKnightTrilogy",
		keywords: ["Hero", "Chaos", "Villain"],
		ageRating: "12A",
		rating: "8.3/10",
		desc: "After witnessing his parents' death, billionaire Bruce Wayne learns the art of fighting to confront injustice. When he returns to Gotham as Batman, he must stop a secret society that intends to destroy the city.",
		similar: ["Tenet", "TheBatman", "BatmanSuperman", "SuicideSquad1"],
		sequels: ["TheDarkKnight2","TheDarkKnight3"],
        poster: "movies/darkknight/darkknight1.jpg",
        link: "https://www.warnerbros.com/movies/batman-begins",
        trailer: "neY2xVmOfUM"
	},
	"TheDarkKnight3": {
		title: "The Dark Knight Rises",
		year: 2012,
		runtime: "2h 44m",
		genres: ["Action", "Drama", "Crime", "Superhero"],
		director: "Christopher Nolan",
		cast: ["Christian Bale", "Joseph Gordon-Levitt", "Anne Hathaway", "Marion Cotillard", "Michael Caine", "Morgan Freeman", "Gary Oldman"],
		franchise: "DarkKnightTrilogy",
		keywords: ["Hero", "Chaos", "Villain"],
		ageRating: "12A",
		rating: "8.3/10",
		desc: "Bane, an imposing terrorist, attacks Gotham City and disrupts its eight-year-long period of peace. This forces Bruce Wayne to come out of hiding and don the cape and cowl of Batman again.",
		similar: ["Tenet", "TheBatman", "BatmanSuperman", "SuicideSquad1"],
		sequels: ["TheDarkKnight1","TheDarkKnight2"],
        poster: "movies/darkknight/darkknight3.jpg",
        link: "https://www.warnerbros.com/movies/dark-knight-rises",
        trailer: "g8evyE9TuYk"
	},
	"TheBatman": {
		title: "The Batman",
		year: 2022,
		runtime: "2h 56m",
		genres: ["Action", "Drama", "Crime", "Superhero"],
		director: "Matt Reeves",
		cast: ["Robert Pattinson", "Zoe Kravitz", "Paul Dano", "Colin Farrell", "Jeffrey Wright", "John Turturro", "Andy Serkis"],
		franchise: null,
		keywords: ["Hero", "Chaos", "Villain"],
		ageRating: "15",
		rating: "8.1/10",
		desc: "When a sadistic serial killer begins murdering key political figures in Gotham, the Batman is forced to investigate the city's hidden corruption and question his family's involvement.",
		similar: ["TheDarkKnight1", "TheDarkKnight2", "TheDarkKnight3", "BatmanSuperman"],
		sequels: [],
        poster: "movies/thebatman/thebatman.jpg",
        link: "https://www.warnerbros.com/movies/the-batman",
        trailer: "mqqft2x_Aa4"
	},
	"BatmanSuperman": {
		title: "Batman v Superman: Dawn of Justice",
		year: 2016,
		runtime: "2h 31m",
		genres: ["Action", "Drama", "Superhero", "Sci-Fi"],
		director: "Zack Snyder",
		cast: ["Ben Affleck", "Henry Cavill", "Jesse Eisenberg", "Gal Gadot", "Jeremy Irons", "Holly Hunter"],
		franchise: null,
		keywords: ["Batman", "Superman", "Justice", "Hero", "Villain"],
		ageRating: "12A",
		rating: "7.2/10",
		desc: "Batman is manipulated by Lex Luthor to fear Superman. Superman´s existence is meanwhile dividing the world and he is framed for murder during an international crisis. The heroes clash and force the neutral Wonder Woman to reemerge.",
		similar: ["TheBatman", "TheDarkKnight1", "TheDarkKnight2", "TheDarkKnight3", "SuicideSquad1"],
		sequels: ["TheDarkKnight1","TheDarkKnight2"],
        poster: "movies/darkknight/darkknight3.jpg",
        link: "https://www.warnerbros.com/movies/batman-v-superman-dawn-justice",
        trailer: "0WWzgGyAH6Y"
	},
	"SuicideSquad1": {
		title: "Suicide Squad",
		year: 2016,
		runtime: "2h 10m",
		genres: ["Action", "Fantasy", "Drama", "Superhero", "Sci-Fi"],
		director: "James Gunn",
		cast: ["Margot Robbie", "Jared Leto", "Will Smith", "Joel Kinnaman", "Viola Davis", "Jai Courtney", "Scott Eastwood", "David Harbour", "Common"],
		franchise: "SSquad",
		keywords: ["Mission", "DC", "Team"],
		ageRating: "15",
		rating: "7.2/10",
		desc: "A secret government agency recruits some of the most dangerous incarcerated super-villains to form a defensive task force. Their first mission: save the world from the apocalypse.",
		similar: ["TheDarkKnight1","TheDarkKnight2","TheDarkKnight3","BatmanSuperman"],
		sequels: ["SuicideSquad2"],
        poster: "movies/suicidesquad/suicidesquad1.jpg",
        link: "https://www.warnerbros.com/movies/suicide-squad",
        trailer: "CmRih_VtVAs"
	},
	"SuicideSquad2": {
		title: "The Suicide Squad",
		year: 2021,
		runtime: "2h 12m",
		genres: ["Action", "Fantasy", "Drama", "Superhero", "Sci-Fi"],
		director: "James Gunn",
		cast: ["Margot Robbie", "John Cena", "Nathan Fillion", "Daniela Melchior", "Idris Elba", "Joel Kinnaman", "David Dastmalchian", "Jennifer Holland", "Peter Capaldi"],
		franchise: "SSquad",
		keywords: ["Mission", "DC", "Team"],
		ageRating: "15",
		rating: "7.3/10",
		desc: "Supervillains Harley Quinn, Bloodsport, Peacemaker, and a collection of nutty cons at Belle Reve prison join the super-secret, super-shady Task Force X as they are dropped off at the remote, enemy-infused island of Corto Maltese.",
		similar: ["TheDarkKnight1","TheDarkKnight2","TheDarkKnight3","BatmanSuperman"],
		sequels: ["SuicideSquad2"],
        poster: "movies/suicidesquad/suicidesquad2.jpg",
        link: "https://www.warnerbros.com/movies/the-suicide-squad",
        trailer: "eg5ciqQzmK0"
	},
	"ForrestGump": {
		title: "Forrest Gump",
		year: 1994,
		runtime: "2h 22m",
		genres: ["Comedy", "Adventure", "Drama"],
		director: "Robert Zemeckis",
		cast: ["Tom Hanks", "Robin Wright", "Gary Sinise", "Sally Field"],
		franchise: null,
		keywords: ["History", "War", "Idiot"],
		ageRating: "12",
		rating: "9.4/10",
		desc: "The history of the United States from the 1950s to the '70s unfolds from the perspective of an Alabama man with an IQ of 75, who yearns to be reunited with his childhood sweetheart.",
		similar: [],
		sequels: [],
        poster: "movies/forrestgump/forrestgump.jpg",
        link: "https://www.paramountmovies.com/movies/forrest-gump",
        trailer: "bLvqoHBptjg"
	},
	"Alien1": {
		title: "Alien",
		year: 1979,
		runtime: "1h 57m",
		genres: ["Horror", "Sci-Fi", "Action"],
		director: "Ridley Scott",
		cast: ["Sigourney Weaver", "Tom Skerritt", "Veronica Cartwright", "John Hurt", "Ian Holm", "Harry Dean Stanton", "Bolaji Badejo"],
		franchise: "Alien",
		keywords: ["Alien", "Space"],
		ageRating: "15",
		rating: "8.7/10",
		desc: "After investigating a mysterious transmission of unknown origin, the crew of a commercial spacecraft encounters a deadly lifeform.",
		similar: ["TheThing", "TheThing2", "Oxygen"],
		sequels: ["Alien2", "Alien3", "Alien4", "Alien5"],
        poster: "movies/alien/alien.jpg",
        link: "https://www.20thcenturystudios.com/movies/alien",
        trailer: "LjLamj-b0I8"
	},
	"Alien2": {
		title: "Aliens",
		year: 1986,
		runtime: "2h 17m",
		genres: ["Horror", "Sci-Fi", "Action"],
		director: "James Cameron",
		cast: ["Sigourney Weaver", "Carrie Henn", "Bill Paxton", "Michael Biehn", "Lance Henriksen", "Paul Reiser"],
		franchise: "Alien",
		keywords: ["Alien", "Space"],
		ageRating: "15",
		rating: "9/10",
		desc: "Decades after surviving the Nostromo incident, Ellen Ripley is sent out to re-establish contact with a terraforming colony but finds herself battling the Alien Queen and her offspring.",
		similar: ["TheThing", "TheThing2", "Oxygen"],
		sequels: ["Alien1", "Alien3", "Alien4", "Alien5"],
        poster: "movies/alien/aliens.jpg",
        link: "https://www.20thcenturystudios.com/movies/aliens",
        trailer: "XKSQmGWaQ94"
	},
	"Alien3": {
		title: "Alien 3",
		year: 1992,
		runtime: "1h 54m",
		genres: ["Horror", "Sci-Fi", "Action"],
		director: "David Fincher",
		cast: ["Sigourney Weaver", "Charles Dance", "David Giler", "Terry Rawlings", "Lance Henriksen", "Pete Postlethwaite", "Brian Glover", "Ralph Brown"],
		franchise: "Alien",
		keywords: ["Alien", "Space"],
		ageRating: "15",
		rating: "8.3/10",
		desc: "Returning from LV-426, Ellen Ripley crash-lands on the maximum-security prison Fiorina 161, where she discovers that she has unwittingly brought along an unwelcome visitor.",
		similar: ["TheThing", "TheThing2", "Oxygen"],
		sequels: ["Alien1", "Alien2", "Alien4", "Alien5"],
        poster: "movies/alien/alien3.jpg",
        link: "https://www.20thcenturystudios.com/movies/alien-3",
        trailer: "M94I16hf3j0"
	},
	"Alien4": {
		title: "Alien Resurrection",
		year: 1997,
		runtime: "1h 49m",
		genres: ["Horror", "Sci-Fi", "Action"],
		director: "Jean-Pierre Jeunet",
		cast: ["Sigourney Weaver", "Winona Ryder", "Ron Perlman", "Dominique Pinon", "Kim Flowers", "Brad Dourif", "Michael Wincott"],
		franchise: "Alien",
		keywords: ["Alien", "Space"],
		ageRating: "15",
		rating: "8.3/10",
		desc: "Two centuries after her death, a powerful human/alien hybrid clone of Ellen Ripley aids a crew of space pirates in stopping the aliens from reaching Earth.",
		similar: ["TheThing", "TheThing2", "Oxygen"],
		sequels: ["Alien1", "Alien2", "Alien3", "Alien5"],
        poster: "movies/alien/alien4.jpg",
        link: "https://www.20thcenturystudios.com/movies/alien-resurrection",
        trailer: "4Z8J_zE8xVw"
	},
	"Alien5": {
		title: "AVP: Alien vs. Predator",
		year: 2004,
		runtime: "1h 41m",
		genres: ["Horror", "Sci-Fi", "Action"],
		director: "Paul W. S. Anderson",
		cast: ["Ian Whyte", "Sanaa Lathan", "Tom Woodruff Jr.", "Lance Henriksen", "Alec Gillis", "Colin Salmon", "Ewen Bremner", "Raoul Bova"],
		franchise: "Alien",
		keywords: ["Alien", "Space"],
		ageRating: "15",
		rating: "8.1/10",
		desc: "During an archaeological expedition on Bouvetøya Island in Antarctica, a team of archaeologists and other scientists find themselves caught up in a battle between the two legends. Soon, the team realize that only one species can win.",
		similar: ["TheThing", "TheThing2", "Oxygen"],
		sequels: ["Alien1", "Alien2", "Alien3", "Alien 4"],
        poster: "movies/alien/alienvpred.jpg",
        link: "https://www.20thcenturystudios.com/movies/avp-alien-vs-predator",
        trailer: "-p7C5v9r-Yk"
	},
	"TheThing": {
		title: "The Thing",
		year: 1982,
		runtime: "1h 49m",
		genres: ["Horror", "Sci-Fi", "Suspense", "Mystery"],
		director: "John Carpenter",
		cast: ["Kurt Russell", "Keith David", "Wilford Brimley", "Richard Masur", "T. K. Carter", "David Clennon", "Donald Moffat"],
		franchise: "TheThing",
		keywords: ["Alien", "Imposter"],
		ageRating: "18",
		rating: "8.7/10",
		desc: "A research team in Antarctica is hunted by a shape-shifting alien that assumes the appearance of its victims.",
		similar: ["Alien", "Aliens", "Oxygen", "Krampus"],
		sequels: ["The Thing"],
        poster: "movies/thething/thething.jpg",
        link: "https://www.imdb.com/title/tt0084787/",
        trailer: "5ftmr17M-P4"
	},
	"TheThing2": {
		title: "The Thing",
		year: 2011,
		runtime: "1h 43m",
		genres: ["Horror", "Sci-Fi", "Suspense", "Mystery"],
		director: "Matthijs van Heijningen Jr.",
		cast: ["Mary Elizabeth Winstead", "Joel Edgerton", "Ulrich Thomsen", "Adewale Akinnuoye", "Kim Bubbs", "Kristofer Hivju", "Eric Christian Olsen", "Trond Espen Seim"],
		franchise: "TheThing",
		keywords: ["Alien", "Imposter"],
		ageRating: "15",
		rating: "8/10",
		desc: "A group of scientists researching an alien spaceship found in the Antarctic come face to face with the ship's, not quite dead, occupant.",
		similar: ["Oxygen"],
		sequels: ["Alien", "Aliens", "The Thing"],
        poster: "movies/thething/thething2.jpg",
        link: "https://www.imdb.com/title/tt0905372/",
        trailer: "Txjm94GnrPA"
	},
	"KPopDemonHunters": {
		title: "KPop Demon Hunters",
		year: 2025,
		runtime: "1h 39m",
		genres: ["Animation", "Musical", "Action"],
		director: "Maggie Kang",
		cast: ["Ken Jeong", "Arden Cho", "Liza Koshy", "May Hong", "SungWon Cho", "Daniel Dae Kim", "Yunjin Kim"],
		franchise: null,
		keywords: [],
		ageRating: "PG",
		rating: "8.3/10",
		desc: "A world-renowned K-Pop girl group balance their lives in the spotlight with their secret identities as demon hunters.",
		similar: [],
		sequels: [],
		poster: "movies/kpopdemonhunters/kpopdemonhunters.jpg",
		link: "https://www.imdb.com",
        trailer: "dQw4w9WgXcQ" // Generic/Placeholder
	},
	"Superman": {
		title: "Superman",
		year: 2025,
		runtime: "2h 10m",
		genres: ["Action","Sci-Fi","Superhero"],
		director: "James Gunn",
		cast: ["David Corenswet", "Rachel Brosnahan", "Nicholas Hoult", "Isabela Merced", "Milly Alcock", "Mikaela Hoover", "Nathan Fillion", "Sara Sampaio"],
		franchise: null,
		keywords: ["DC"],
		ageRating: "12A",
		rating: "8.5/10",
		desc: "Superman must reconcile his alien Kryptonian heritage with his human upbringing as reporter Clark Kent. As the embodiment of truth, justice and the human way he soon finds himself in a world that views these as old-fashioned.",
		similar: ["BatmanSuperman"],
		sequels: [],
		poster: "movies/superman/superman.jpg",
		link: "https://www.imdb.com",
        trailer: "dQw4w9WgXcQ" // Generic/Placeholder
	},
	"F1": {
		title: "F1",
		year: 2025,
		runtime: "2h 35m",
		genres: ["Action", "Sport", "Adventure"],
		director: "Joseph Kosinski",
		cast: ["Brad Pitt", "Kerry Condon", "Damson Idris", "Javier Bardem", "Lewis Hamilton", "Max Verstappen", "Callie Cooke", "Lando Norris"],
		franchise: null,
		keywords: ["Racing", "Cars"],
		ageRating: "12A",
		rating: "8.9/10",
		desc: "A Formula One driver comes out of retirement to mentor and team up with a younger driver.",
		similar: [],
		sequels: [],
		poster: "movies/F1/F1.jpg",
		link: "https://www.imdb.com",
        trailer: "a27X-2849aw" // F1 Teaser
	},
	"Frankenstein": {
		title: "Frankenstein",
		year: 2025,
		runtime: "2h 29m",
		genres: ["Horror", "Sci-Fi", "Adventure", "Drama"],
		director: "Guillermo del Toro",
		cast: ["Jacob Elordi", "Mia Goth", "Oscar Isaac", "Christoph Waltz", "Felix Kammerer", "Charles Dance", "Ralph Ineson", "Sofia Galasso"],
		franchise: null,
		keywords: ["Monster", "Scientist"],
		ageRating: "15",
		rating: "9.2/10",
		desc: "Dr. Victor Frankenstein, a brilliant but egotistical scientist, brings a creature to life in a monstrous experiment that ultimately leads to the undoing of both the creator and his tragic creation.",
		similar: [],
		sequels: [],
		poster: "movies/frankenstein/frankenstein.jpg",
		link: "https://www.imdb.com",
        trailer: "dQw4w9WgXcQ" // Generic/Placeholder
	},
	"Wicked1": {
		title: "Wicked",
		year: 2024,
		runtime: "2h 40m",
		genres: ["Fantasy", "Musical", "Drama"],
		director: "Jon M. Chu",
		cast: ["Cynthia Erivo", "Ariana Grande", "Jonathan Bailey", "Ethan Slater", "Michelle Yeoh", "Marissa Bode", "Jeff Goldblum", "Peter Dinklage"],
		franchise: "Wicked",
		keywords: ["Witch", "Magical"],
		ageRating: "PG",
		rating: "7.8/10",
		desc: "Elphaba, a young woman ridiculed for her green skin, and Galinda, a popular girl, become friends at Shiz University in the Land of Oz. After an encounter with the Wonderful Wizard of Oz, their friendship reaches a crossroads.",
		similar: [],
		sequels: ["Wicked2"],
		poster: "movies/wicked/wicked.jpg",
		link: "https://www.universalpictures.com/movies/wicked",
        trailer: "F1W2t6n3aQ" // Wicked Trailer
	},
	"Wicked2": {
		title: "Wicked: For Good",
		year: 2025,
		runtime: "2h 17m",
		genres: ["Fantasy", "Musical", "Drama"],
		director: "Jon M. Chu",
		cast: ["Cynthia Erivo", "Ariana Grande", "Jonathan Bailey", "Ethan Slater", "Michelle Yeoh", "Marissa Bode", "Jeff Goldblum", "Peter Dinklage"],
		franchise: "Wicked",
		keywords: ["Witch", "Magical"],
		ageRating: "PG",
		rating: "8.6/10",
		desc: "Elphaba, the future Wicked Witch of the West and her relationship with Glinda, the Good Witch of the North. The second of a two-part feature film adaptation of the Broadway musical.",
		similar: [],
		sequels: ["Wicked1"],
		poster: "movies/wicked/wickedforgood.jpg",
		link: "https://www.imdb.com",
        trailer: "dQw4w9WgXcQ" // Generic/Placeholder
	},
	"HappyGilmore2": {
		title: "Happy Gilmore 2",
		year: 2025,
		runtime: "1h 58m",
		genres: ["Comedy", "Action"],
		director: "Kyle Newacheck",
		cast: ["Bad Bunny", "Eminem", "Travis Kelce", "Margaret Qualley", "John Daly", "Sunny Sandler", "Haley Joel Osment", "Benny Safdie"],
		franchise: null,
		keywords: ["Golf", "Satire"],
		ageRating: "12A",
		rating: "7.4/10",
		desc: "To provide for his family, a retired Happy Gilmore must pick up the golf clubs once more and reconnect with the sport he once dominated.",
		similar: [],
		sequels: ["HappyGilmore"], 
		poster: "movies/happygilmore/happygilmore2.jpg",
		link: "https://www.imdb.com",
        trailer: "dQw4w9WgXcQ" // Generic/Placeholder
	},
	"Zootropolis2": {
		title: "Zootropolis 2",
		year: 2025,
		runtime: "1h 48m",
		genres: ["Animation", "Comedy", "Adventure"],
		director: ["Jared Bush", "Byron Howard"],
		cast: ["Shakira", "Ke Huy Quan", "Macaulay Culkin", "Quinta Brunson", "Fortune Feimster", "Patrick Warburton", "Robert Irwin", "Josh Dallas"],
		franchise: "Zootropolis",
		keywords: ["Animals", "Cartoon"],
		ageRating: "PG",
		rating: "9.4/10",
		desc: "Brave rabbit cop Judy Hopps and her friend, the fox Nick Wilde, team up again to crack a new case, the most perilous and intricate of their careers.",
		similar: [],
		sequels: ["Zootropolis1"], 
		poster: "movies/zootropolis/zootropolis2.jpg",
		link: "https://www.imdb.com",
        trailer: "dQw4w9WgXcQ" // Generic/Placeholder
	},
	"TrainDreams": {
		title: "Train Dreams",
		year: 2025,
		runtime: "1h 42m",
		genres: ["Drama"],
		director: "Clint Bentley",
		cast: ["Joel Edgerton", "Felicity Jones", "Will Patton", "Kerry Condon", "William H. Macy", "John Diehl", "Paul Schneider", "Nathaniel Arcand"],
		franchise: null,
		keywords: ["Immigrant", "Grief"],
		ageRating: "12A",
		rating: "7.4/10",
		desc: "Based on Denis Johnson's beloved novella, Train Dreams is the moving portrait of Robert Grainier, a logger and railroad worker who leads a life of unexpected depth and beauty in the rapidly-changing America of the early 20th Century.",
		similar: [],
		sequels: [],
		poster: "movies/traindreams/traindreams.jpg",
		link: "https://www.imdb.com",
        trailer: "dQw4w9WgXcQ" // Generic/Placeholder
	},
	"Avatar3": {
		title: "Avatar: Fire and Ash",
		year: 2025,
		runtime: "3h 17m",
		genres: ["Action", "Fantasy", "Animation", "Adventure", "Sci-Fi"],
		director: "James Cameron",
		cast: ["Zoe Saldana", "Sam Worthington", "Sigourney Weaver", "Stephen Lang", "Oona Chaplin", "Kate Winslet", "Michelle Yeoh", "David Thewlis"],
		franchise: "Avatar",
		keywords: ["Tribes", "Grief"],
		ageRating: "12A",
		rating: "-/10",
		desc: "Jake and Neytiri's family grapples with grief after Neteyam's death, encountering a new, aggressive Na'vi tribe, the Ash People, who are led by the fiery Varang, as the conflict on Pandora escalates and a new moral focus emerges.",
		similar: [],
		sequels: ["Avatar1", "Avatar2"],
		poster: "movies/avatar/avatar3.jpg",
		link: "https://www.imdb.com",
        trailer: "dQw4w9WgXcQ" // Generic/Placeholder
	},
	"Spideman1": {
		title: "Spider-Man: Homecoming",
		year: 2017,
		runtime: "2h 13m",
		genres: ["Action", "Adventure", "Sci-Fi", "Superhero"],
		director: "Jon Watts",
		cast: ["Tom Holland", "Michael Keaton", "Robert Downey Jr.", "Zendaya", "Jacob Batalon"],
		franchise: "Spiderman",
		keywords: ["Marvel", "High School", "Vulture"],
		ageRating: "12A",
		rating: "7.4/10",
		desc: "Peter Parker balances his life as an ordinary high school student in Queens with his superhero alter-ego Spider-Man, and finds himself on the trail of a new menace prowling the skies of New York City.",
		similar: ["SpidermanTobey1", "SpidermanTobey2", "TheBatman"],
		sequels: ["Spideman2", "Spiderman3", "Spiderman4", "Spiderman5"],
		poster: "movies/spiderman/homecoming.jpg",
		link: "https://www.netflix.com/title/80166369",
		trailer: "n9DwoQ7HWvI"
	},
	"Spideman2": {
		title: "Spider-Man: Far From Home",
		year: 2019,
		runtime: "2h 09m",
		genres: ["Action", "Adventure", "Sci-Fi", "Superhero"],
		director: "Jon Watts",
		cast: ["Tom Holland", "Samuel L. Jackson", "Zendaya", "Jake Gyllenhaal", "Jacob Batalon"],
		franchise: "Spiderman",
		keywords: ["Marvel", "Europe", "Illusion"],
		ageRating: "12A",
		rating: "7.4/10",
		desc: "Following the events of Avengers: Endgame, Spider-Man must step up to take on new threats in a world that has changed forever.",
		similar: ["SpidermanTobey1", "SpidermanTobey2", "Inception"],
		sequels: ["Spideman1", "Spiderman3", "Spiderman4", "Spiderman5"],
		poster: "movies/spiderman/farfromhome.jpg",
		link: "https://www.netflix.com/title/81055822",
		trailer: "Nt9L1jCKGnE"
	},
	"Spiderman3": {
		title: "Spider-Man: No Way Home",
		year: 2021,
		runtime: "2h 28m",
		genres: ["Action", "Adventure", "Sci-Fi", "Superhero"],
		director: "Jon Watts",
		cast: ["Tom Holland", "Zendaya", "Benedict Cumberbatch", "Jacob Batalon", "Jamie Foxx", "Willem Dafoe", "Alfred Molina"],
		franchise: "Spiderman",
		keywords: ["Marvel", "Multiverse", "Magic"],
		ageRating: "12A",
		rating: "8.2/10",
		desc: "With Spider-Man's identity now revealed, Peter asks Doctor Strange for help. When a spell goes wrong, dangerous foes from other worlds start to appear, forcing Peter to discover what it truly means to be Spider-Man.",
		similar: ["SpidermanTobey1", "SpidermanTobey2", "SpidermanTobey3", "DoctorStrange"],
		sequels: ["Spideman1", "Spideman2", "Spiderman5"],
		poster: "movies/spiderman/nowayhome.jpg",
		link: "https://www.netflix.com/title/81231660",
		trailer: "JfVOs4VSpmA"
	},
	"Spiderman4": {
		title: "Spider-Man: Brand New Day",
		year: 2026,
		runtime: "3h 17m",
		genres: ["Action", "Adventure", "Sci-Fi", "Superhero"],
		director: "Destin Daniel Cretton",
		cast: ["Sadie Pink", "Tom Holland", "Zendaya", "Jon Bernthal", "Michael Mando", "Jacob Batalon", "Mark Ruffalo", "Krondon"],
		franchise: "Spiderman",
		keywords: ["Marvel"],
		ageRating: "12A",
		rating: "-/10",
		desc: "Peter Parker tries to focus on college and leave Spider-Man behind. But when a new threat endangers his friends, he must break his promise and suit up again, teaming with an unexpected ally to protect those he loves.",
		similar: [],
		sequels: ["Spideman1","Spideman2","Spiderman3","Spiderman4"], 
		poster: "movies/spiderman/spidermanbrandnewday.jpg",
		link: "https://www.imdb.com",
        trailer: "dQw4w9WgXcQ" // Generic/Placeholder
	},
	"SpidermanTobey1": {
		title: "Spider-Man",
		year: 2002,
		runtime: "2h 01m",
		genres: ["Action", "Adventure", "Sci-Fi", "Superhero"],
		director: "Sam Raimi",
		cast: ["Tobey Maguire", "Willem Dafoe", "Kirsten Dunst", "James Franco", "Cliff Robertson"],
		franchise: "Spiderman",
		keywords: ["Marvel", "Origin", "Green Goblin"],
		ageRating: "12A",
		rating: "7.4/10",
		desc: "When bitten by a genetically modified spider, a nerdy, shy, and awkward high school student gains spider-like abilities that he must eventually use to fight evil as a superhero after tragedy befalls his family.",
		similar: ["Spideman1", "Spideman2", "Spiderman3", "TheDarkKnight1"],
		sequels: ["SpidermanTobey2", "SpidermanTobey3"],
		poster: "movies/spiderman/tobey1.jpg",
		link: "https://www.disneyplus.com/movies/spider-man/4M1e7Kr5f3fC",
		trailer: "t06RUxPbp_c"
	},
	"SpidermanTobey2": {
		title: "Spider-Man 2",
		year: 2004,
		runtime: "2h 07m",
		genres: ["Action", "Adventure", "Sci-Fi", "Superhero"],
		director: "Sam Raimi",
		cast: ["Tobey Maguire", "Kirsten Dunst", "James Franco", "Alfred Molina", "Rosemary Harris"],
		franchise: "Spiderman",
		keywords: ["Marvel", "Train", "Doc Ock"],
		ageRating: "PG",
		rating: "7.5/10",
		desc: "Peter Parker is beset with troubles in his failing personal life as he battles a brilliant scientist named Doctor Otto Octavius.",
		similar: ["Spideman1", "Spideman2", "Spiderman3", "TheDarkKnight2"],
		sequels: ["SpidermanTobey1", "SpidermanTobey3"],
		poster: "movies/spiderman/tobey2.jpg",
		link: "https://www.disneyplus.com/movies/spider-man-2/4M1e7Kr5f3fC",
		trailer: "1s9Yln0YlLw"
	},
	"SpidermanTobey3": {
		title: "Spider-Man 3",
		year: 2007,
		runtime: "2h 19m",
		genres: ["Action", "Adventure", "Sci-Fi", "Superhero"],
		director: "Sam Raimi",
		cast: ["Tobey Maguire", "Kirsten Dunst", "James Franco", "Thomas Haden Church", "Topher Grace"],
		franchise: "Spiderman",
		keywords: ["Marvel", "Symbiote", "Sandman"],
		ageRating: "12A",
		rating: "6.3/10",
		desc: "A strange black entity from another world bonds with Peter Parker and causes inner turmoil as he contends with new villains, temptations, and revenge.",
		similar: ["Spideman1", "Spideman2", "Spiderman3", "Venom"],
		sequels: ["SpidermanTobey1", "SpidermanTobey2"],
		poster: "movies/spiderman/tobey3.jpg",
		link: "https://www.disneyplus.com/movies/spider-man-3/4M1e7Kr5f3fC",
		trailer: "wPosLpgMtTY"
	},
	"AmazingSpiderman1": {
		title: "The Amazing Spider-Man",
		year: 2012,
		runtime: "2h 16m",
		genres: ["Action", "Adventure", "Sci-Fi", "Superhero"],
		director: "Marc Webb",
		cast: ["Andrew Garfield", "Emma Stone", "Rhys Ifans", "Denis Leary", "Martin Sheen", "Sally Field"],
		franchise: "Spiderman",
		keywords: ["Marvel", "Lizard", "Reboot", "High School"],
		ageRating: "12A",
		rating: "6.9/10",
		desc: "After Peter Parker is bitten by a genetically altered spider, he gains newfound, spider-like powers and ventures out to save the city from the machinations of a mysterious reptilian foe.",
		similar: ["SpidermanTobey1", "Spideman1", "TheBatman"],
		sequels: ["AmazingSpiderman2"],
		poster: "movies/spiderman/tasm1.jpg",
		link: "https://www.netflix.com/title/70208599",
		trailer: "FpKPiHYJc54"
	},
	"AmazingSpiderman2": {
		title: "The Amazing Spider-Man 2",
		year: 2014,
		runtime: "2h 22m",
		genres: ["Action", "Adventure", "Sci-Fi", "Superhero"],
		director: "Marc Webb",
		cast: ["Andrew Garfield", "Emma Stone", "Jamie Foxx", "Dane DeHaan", "Paul Giamatti", "Sally Field"],
		franchise: "Spiderman",
		keywords: ["Marvel", "Electro", "Green Goblin", "Tragedy"],
		ageRating: "12A",
		rating: "6.6/10",
		desc: "When New York is put under siege by Oscorp, it is up to Spider-Man to save the city he swore to protect as well as his loved ones.",
		similar: ["SpidermanTobey2", "Spideman2", "Spiderman3"],
		sequels: ["AmazingSpiderman1"],
		poster: "movies/spiderman/tasm2.jpg",
		link: "https://www.netflix.com/title/70293701",
		trailer: "DlM2CWNTQ84"
	},
	"Odyssey": {
		title: "The Odyssey",
		year: 2026,
		runtime: "-h -m",
		genres: ["Action", "Fantasy", "Adventure"],
		director: "Christopher Nolan",
		cast: ["Matt Damon", "Mia Goth", "Anne Hathaway"],
		franchise: null,
		keywords: ["Trojan", "Monster", "Ocean"],
		ageRating: "12A",
		rating: "-/10",
		desc: "After the Trojan War, Odysseus faces a dangerous voyage back to Ithaca, meeting creatures like the Cyclops Polyphemus, Sirens, and Circe along the way.",
		similar: [],
		sequels: [],
		poster: "movies/theodyssey/theodyssey.jpg",
		link: "https://www.imdb.com",
        trailer: "dQw4w9WgXcQ" // Generic/Placeholder
	},
	"ToyStory5": {
		title: "Toy Story 5",
		year: 2026,
		runtime: "-h -m",
		genres: ["Animation", "Comedy", "Adventure"],
		director: "Andrew Stanton",
		cast: ["Tom Hanks", "Tim Allen", "Ernie Hudson", "Joan Cusack"],
		franchise: "ToyStory",
		keywords: ["Trojan", "Monster", "Ocean"],
		ageRating: "U",
		rating: "-/10",
		desc: "Buzz, Woody, Jessie are challenged after being introduced to what kids are obsessed with today: electronics.",
		similar: [],
		sequels: ["ToyStory1","ToyStory2","ToyStory3","ToyStory4"],
		poster: "movies/toystory/toystory5.jpg",
		link: "https://www.imdb.com",
        trailer: "dQw4w9WgXcQ" // Generic/Placeholder
	},
	"Scream7": {
		title: "Scream 7",
		year: 2026,
		runtime: "-h -m",
		genres: ["Horror", "Mystery"],
		director: "Kevin Williamson",
		cast: ["Neve Campbell", "Courtney Cox", "Isabel May", "Matthew Lillard", "Mason Gooding", "David Arquette"],
		franchise: "Scream",
		keywords: ["Slasher", "Mask"],
		ageRating: "18",
		rating: "-/10",
		desc: "When a new Ghostface killer emerges in the town where Sidney Prescott has built a new life, her darkest fears are realized as her daughter becomes the next target.",
		similar: [],
		sequels: ["Scream","Scream2","Scream3","Scream4","Scream5","Scream6"], 
		poster: "movies/scream/scream7.jpg",
		link: "https://www.imdb.com",
        trailer: "dQw4w9WgXcQ" // Generic/Placeholder
	},
	"GreenMile": {
		title: "Green Mile",
		year: 1999,
		runtime: "3h 09m",
		genres: ["Horror", "Drama", "Crime"],
		director: "Frank Darabont",
		cast: ["Michael Clarke Duncan", "Tom Hanks", "David Morse", "Sam Rockwell", "Michael Jeter", "James Cromwell", "Doug Hutchison", "Barry Pepper"],
		franchise: null,
		keywords: ["Innocence", "Justice", "Execution"],
		ageRating: "18",
		rating: "9.1/10",
		desc: "A death row guard learns that a gentle giant in his charge possesses a mysterious gift.",
		similar: [],
		sequels: [],
		poster: "movies/greenmile/greenmile.jpg",
		link: "https://www.warnerbros.com",
        trailer: "Ki4haFrq0sg"
	},
	"ChristmasWithTheKranks": {
		title: "Christmas With The Kranks",
		year: 2004,
		runtime: "1h 38m",
		genres: ["Family", "Comedy", "Drama", "Christmas"],
		director: "Joe Roth",
		cast: ["Tim Allen", "Jamie Lee Curtis", "Dan Aykroyd", "Julie Gonzalo", "Erik Per Sullivan", "Jake Busey", "M. Emmet Walsh", "Cheech Marin"],
		franchise: null,
		keywords: ["Snowman", "Cruise", "Holiday"],
		ageRating: "PG",
		rating: "7.3/10",
		desc: "With their daughter Blair away in Peru, Luther and Nora Krank decide to skip Christmas altogether until she decides to come home, causing an uproar when they must celebrate it at the last minute.",
		similar: ["HomeAlone", "Elf"],
		sequels: [],
		poster: "movies/christmaswiththekranks/cwtk.jpg",
		link: "https://www.netflix.com/gb/title/70011207",
        trailer: "KTzyGuB9V6c"
	},
	"HomeAlone": {
		title: "Home Alone",
		year: 1990,
		runtime: "1h 43m",
		genres: ["Comedy", "Family", "Christmas"],
		director: "Chris Columbus",
		cast: ["Macaulay Culkin", "Joe Pesci", "Daniel Stern", "John Heard", "Catherine O'Hara", "Kieran Culkin", "John Heard", "Devin Ratray"],
		franchise: "HomeAlone",
		keywords: ["Burglar", "Trap", "Holiday"],
		ageRating: "PG",
		rating: "8.9/10",
		desc: "An eight-year-old troublemaker, mistakenly left home alone, must defend his home against a pair of burglars on Christmas Eve.",
		similar: ["ChristmasWithTheKranks", "Elf", "TheGrinchIllumination"],
		sequels: ["HomeAlone2"], 
		poster: "movies/homealone/homealone.jpg", 
		link: "https://www.disneyplus.com/movies/home-alone",
		trailer: "jEDaVHmw7r4"
	},
	"HomeAlone2": {
		title: "Home Alone 2: Lost in New York",
		year: 1992,
		runtime: "2h 00m",
		genres: ["Comedy", "Family", "Christmas"],
		director: "Chris Columbus",
		cast: ["Macaulay Culkin", "Joe Pesci", "Daniel Stern", "John Heard", "Catherine O'Hara", "Tim Curry", "Devin Ratray"],
		franchise: "HomeAlone",
		keywords: ["Burglar", "Trap", "Holiday"],
		ageRating: "PG",
		rating: "8.9/10",
		desc: "Kevin is separated from his family again when he accidentally boards a flight to New York City during a Christmas trip to Miami. However he crosses paths with the same burglars, who now plan to rob a toy store on Christmas eve.",
		similar: ["ChristmasWithTheKranks", "Elf", "TheGrinchIllumination"],
		sequels: ["HomeAlone"], 
		poster: "movies/homealone/homealone2.jpg", 
		link: "https://www.disneyplus.com/movies/home-alone-2",
		trailer: "5h9VDUNtoto"
	},
	"Krampus": {
		title: "Krampus",
		year: 2015,
		runtime: "1h 38m",
		genres: ["Horror", "Comedy", "Fantasy", "Christmas"],
		director: "Michael Dougherty",
		cast: ["Adam Scott", "Toni Collette", "David Koechner", "Allison Tolman", "Conchata Ferrell"],
		franchise: null,
		keywords: ["Monster", "Snow", "Family"],
		ageRating: "12A",
		rating: "6.6/10",
		desc: "A boy who has a bad Christmas accidentally summons a festive demon to his family home.",
		similar: ["TheThing", "HomeAlone"],
		sequels: [], 
		poster: "movies/krampus/krampus.jpg", 
		link: "https://www.imdb.com/title/tt3431630/",
		trailer: "h6cVyoMH4QE"
	},
	"Elf": {
		title: "Elf",
		year: 2003,
		runtime: "1h 37m",
		genres: ["Family", "Comedy", "Fantasy", "Christmas"],
		director: "Jon Favreau",
		cast: ["Will Ferrell", "James Caan", "Bob Newhart"],
		franchise: null,
		keywords: ["Monster", "Snow", "Family"],
		ageRating: "PG",
		rating: "8.3/10",
		desc: "Raised as an oversized elf, Buddy travels from the North Pole to New York City to meet his biological father, Walter Hobbs, who doesn't know he exists and is in desperate need of some Christmas spirit.",
		similar: ["ChristmasWithTheKranks", "HomeAlone"],
		sequels: [], 
		poster: "movies/elf/elf.jpg", 
		link: "https://www.netflix.com/title/60031255",
		trailer: "a54yC1etmVc"
	},
	"TheGrinchIllumination": {
		title: "The Grinch",
		year: 2018,
		runtime: "1h 25m",
		genres: ["Animation", "Comedy", "Family", "Christmas"],
		director: "Yarrow Cheney",
		cast: ["Benedict Cumberbatch", "Cameron Seely", "Mindy Sterling", "Pharrell Williams", "Angela Lansbury", "Kenan Thompson", "Scarlett Estevez"],
		franchise: null,
		keywords: ["Stealing", "Grinch", "Kindness"],
		ageRating: "U",
		rating: "7.7/10",
		desc: "A grumpy Grinch plots to ruin Christmas for the village of Whoville.",
		similar: ["ChristmasWithTheKranks", "HomeAlone", "Elf", "HomeAlone2"],
		sequels: [], 
		poster: "movies/grinchillumination/grinch.jpg", 
		link: "https://www.netflix.com/title/80996790",
		trailer: "_UOh0UX3alI"
	},
	"DieHard": {
		title: "Die Hard",
		year: 1988,
		runtime: "2h 12m",
		genres: ["Action", "Thriller", "Christmas"],
		director: "John McTiernan",
		cast: ["Bruce Willis", "Alan Rickman", "Bonnie Bedelia", "Reginald VelJohnson"],
		franchise: "DieHard",
		keywords: ["Hostage", "Police", "Heist"],
		ageRating: "15",
		rating: "8.2/10",
		desc: "A New York City police officer tries to save his estranged wife and several others taken hostage by terrorists during a Christmas party at the Nakatomi Plaza in Los Angeles.",
		similar: ["HomeAlone", "TheDarkKnight2"],
		sequels: [], 
		poster: "movies/diehard/diehard.jpg", 
		link: "https://www.disneyplus.com/movies/die-hard",
		trailer: "gYWvwkXX_jM"
	},
	"PolarExpress": {
		title: "The Polar Express",
		year: 2004,
		runtime: "1h 40m",
		genres: ["Animation", "Adventure", "Family", "Fantasy", "Christmas"],
		director: "Robert Zemeckis",
		cast: ["Tom Hanks", "Daryl Sabara", "Nona Gaye", "Jimmy Bennett"],
		franchise: null,
		keywords: ["Train", "Santa", "Belief"],
		ageRating: "U",
		rating: "6.6/10",
		desc: "On Christmas Eve, a young boy embarks on a magical adventure to the North Pole on the Polar Express, while learning about friendship, bravery, and the spirit of Christmas.",
		similar: ["Elf", "TheGrinchIllumination"],
		sequels: [], 
		poster: "movies/polarexpress/polarexpress.jpg", 
		link: "https://www.warnerbros.com/movies/polar-express",
		trailer: "TQhRqtt-Fpo"
	},
	"LoveActually": {
		title: "Love Actually",
		year: 2003,
		runtime: "2h 15m",
		genres: ["Comedy", "Drama", "Romance", "Christmas"],
		director: "Richard Curtis",
		cast: ["Hugh Grant", "Martine McCutcheon", "Liam Neeson", "Emma Thompson", "Alan Rickman", "Colin Firth", "Keira Knightley"],
		franchise: null,
		keywords: ["Romance", "London", "Relationships"],
		ageRating: "15",
		rating: "7.6/10",
		desc: "Follows the lives of eight very different couples in dealing with their love lives in various loosely interrelated tales all set during a frantic month before Christmas in London, England.",
		similar: ["ChristmasWithTheKranks", "Elf"],
		sequels: [], 
		poster: "movies/loveactually/loveactually.jpg", 
		link: "https://www.netflix.com/title/60031262",
		trailer: "H9Z3_ifFheQ"
	},
	"ChristmasVacation": {
		title: "National Lampoon's Christmas Vacation",
		year: 1989,
		runtime: "1h 37m",
		genres: ["Comedy", "Family", "Christmas"],
		director: "Jeremiah S. Chechik",
		cast: ["Chevy Chase", "Beverly D'Angelo", "Juliette Lewis", "Johnny Galecki", "Randy Quaid"],
		franchise: "NationalLampoon",
		keywords: ["Family", "Disaster", "Holiday"],
		ageRating: "12A",
		rating: "7.5/10",
		desc: "The Griswold family's plans for a big family Christmas predictably turn into a big disaster.",
		similar: ["HomeAlone", "ChristmasWithTheKranks", "Elf"],
		sequels: [], 
		poster: "movies/christmasvacation/christmasvacation.jpg", 
		link: "https://www.warnerbros.com/movies/national-lampoons-christmas-vacation",
		trailer: "NBTTipJX-h4"
	},
	"PitchPerfect": {
		title: "Pitch Perfect",
		year: 2012,
		runtime: "1h 52m",
		genres: ["Comedy", "Musical", "Romance"],
		director: "Jason Moore",
		cast: ["Anna Kendrick", "Rebel Wilson", "Brittany Snow", "Anna Camp", "Skylar Astin", "Adam DeVine"],
		franchise: "PitchPerfect",
		keywords: ["A Cappella", "College", "Competition"],
		ageRating: "12A",
		rating: "7.1/10",
		desc: "Beca, a freshman at Barden University, is cajoled into joining The Bellas, her school's all-girls singing group. Injecting some much needed energy into their repertoire, The Bellas take on their male rivals in a campus competition.",
		similar: ["MeanGirls", "SchoolOfRock"],
		sequels: ["PitchPerfect2", "PitchPerfect3"], 
		poster: "movies/pitchperfect/pitchperfect.jpg", 
		link: "https://www.netflix.com/title/70244164",
		trailer: "8dItOM6pJUo"
	},
	"PitchPerfect2": {
		title: "Pitch Perfect 2",
		year: 2015,
		runtime: "1h 55m",
		genres: ["Comedy", "Musical"],
		director: "Elizabeth Banks",
		cast: ["Anna Kendrick", "Rebel Wilson", "Hailee Steinfeld", "Brittany Snow", "Skylar Astin", "Adam DeVine"],
		franchise: "PitchPerfect",
		keywords: ["A Cappella", "World Championship", "College"],
		ageRating: "12A",
		rating: "6.4/10",
		desc: "After a humiliating command performance at The Kennedy Center, the Barden Bellas enter an international competition that no American group has ever won in order to regain their status and right to perform.",
		similar: ["MeanGirls", "SchoolOfRock"],
		sequels: ["PitchPerfect", "PitchPerfect3"], 
		poster: "movies/pitchperfect/pitchperfect2.jpg", 
		link: "https://www.netflix.com/title/80019346",
		trailer: "6p-1oQp2264"
	},
	"PitchPerfect3": {
		title: "Pitch Perfect 3",
		year: 2017,
		runtime: "1h 33m",
		genres: ["Comedy", "Musical"],
		director: "Trish Sie",
		cast: ["Anna Kendrick", "Rebel Wilson", "Brittany Snow", "Anna Camp", "Hailee Steinfeld", "Ruby Rose"],
		franchise: "PitchPerfect",
		keywords: ["A Cappella", "Tour", "Friendship"],
		ageRating: "12A",
		rating: "5.8/10",
		desc: "Following their win at the world championship, the now separated Bellas reunite for one last singing competition at an overseas USO tour, but face a group who uses both instruments and voices.",
		similar: ["MeanGirls", "SchoolOfRock"],
		sequels: ["PitchPerfect", "PitchPerfect2"], 
		poster: "movies/pitchperfect/pitchperfect3.jpg", 
		link: "https://www.netflix.com/title/80192837",
		trailer: "qZkEdPAqip8"
	},
	"Frozen1": {
		title: "Frozen",
		year: 2013,
		runtime: "1h 42m",
		genres: ["Family", "Musical", "Animation", "Adventure"],
		director: ["Jennifer Lee","Chris Buck"],
		cast: ["Kristen Bell", "Idina Menzel", "Jonathan Groff", "Josh Gad", "Santino Fontana"],
		franchise: "Frozen",
		keywords: ["Cold", "Snow", "Sister", "Disney"],
		ageRating: "PG",
		rating: "7.9/10",
		desc: "Fearless optimist Anna teams up with rugged mountain man Kristoff and his loyal reindeer Sven in an epic journey to find Anna's sister Elsa, whose icy powers have trapped the kingdom of Arendelle in eternal winter.",
		similar: ["MonstersUniversity", "ThePirateFairy"],
		sequels: ["Frozen2", "Frozen3"], 
		poster: "movies/frozen/frozen1.jpg", 
		link: "https://www.netflix.com/title/70279000",
		trailer: "TbQm5doF_Uc"
	},
	"Frozen2": {
		title: "Frozen 2",
		year: 2019,
		runtime: "1h 43m",
		genres: ["Family", "Musical", "Animation", "Adventure", "Fantasy"],
		director: ["Jennifer Lee","Chris Buck"],
		cast: ["Kristen Bell", "Idina Menzel", "Jonathan Groff", "Josh Gad", "Santino Fontana", "Sterling K. Brown", "Alfred Molina", "Evan Rachel Wood"],
		franchise: "Frozen",
		keywords: ["Identity", "Magic", "Sister", "Disney"],
		ageRating: "U",
		rating: "8.4/10",
		desc: "Anna, Elsa, Kristoff, Olaf and Sven leave Arendelle to travel to an ancient, autumn-bound forest of an enchanted land. They set out to find the origin of Elsa's powers in order to save their kingdom.",
		similar: ["MonstersUniversity", "ThePirateFairy"],
		sequels: ["Frozen1", "Frozen3"], 
		poster: "movies/frozen/frozen2.jpg", 
		link: "https://www.disneyplus.com/en-gb/browse/entity-3f9272e2-33f1-47db-bb2e-9aa2c7c85a96",
		trailer: "Zi4LMpSDccc"
	},
	"Frozen3": {
		title: "Frozen 3",
		year: 2027,
		runtime: "-h -m",
		genres: ["Family", "Musical", "Animation", "Adventure", "Fantasy"],
		director: ["Jennifer Lee","Marc Smith"],
		cast: ["Kristen Bell", "Idina Menzel", "Jonathan Groff", "Josh Gad", "Santino Fontana", "Sterling K. Brown", "Alfred Molina", "Evan Rachel Wood"],
		franchise: "Frozen",
		keywords: ["Identity", "Magic", "Sister", "Disney"],
		ageRating: "U",
		rating: "8.4/10",
		desc: "Elsa and Anna take Olaf, Kristoff, and Sven for another adventure.",
		similar: ["MonstersUniversity", "ThePirateFairy"],
		sequels: ["Frozen1", "Frozen2"], 
		poster: "movies/frozen/frozen3.jpg", 
		link: "",
		trailer: ""
	},
	"MonstersUniversity": {
		title: "Monsters University",
		year: 2013,
		runtime: "1h 44m",
		genres: ["Family", "Comedy", "Animation", "Adventure"],
		director: "Dan Scanlon",
		cast: ["Billy Crystal", "John Goodman", "Steve Buscemi", "Helen Mirren", "Charlie Day", "Nathan Fillion"],
		franchise: null,
		keywords: ["Friendship", "Monsters", "University", "Disney"],
		ageRating: "U",
		rating: "8.1/10",
		desc: "A look at the relationship between Mike Wazowski and James P. (Sully) Sullivan during their days at Monsters University, when they weren't necessarily the best of friends.",
		similar: ["Frozen1", "ThePirateFairy"],
		sequels: [], 
		poster: "movies/monstersuniversity/mu.jpg", 
		link: "https://www.disneyplus.com/en-gb/browse/entity-9b76e5cf-4005-4f0b-ae54-e65f3a6ccb61",
		trailer: "xBzPioph8CI"
	},
	"ThePirateFairy": {
		title: "The Pirate Fairy",
		year: 2014,
		runtime: "1h 30m",
		genres: ["Family", "Fantasy", "Animation", "Adventure"],
		director: "Peggy Holmes",
		cast: ["Tom Hiddleston", "Christina Hendricks", "Mae Whitman", "Raven-Symone", "Angela Bartys", "Lucy Liu", "Pamela Adlon", "Jeff Bennett"],
		franchise: null,
		keywords: ["Fairy", "Disney", "Ocean"],
		ageRating: "U",
		rating: "6.4/10",
		desc: "Tinker Bell and her friends embark on an adventure when former friend Zarina returns, the rest of Pixie Hollow put to sleep, they set out to face a band of pirates led by a cabin boy who'll soon be known as Captain Hook himself.",
		similar: ["Frozen1", "MonstersUniversity"],
		sequels: [], 
		poster: "movies/piratefairy/pf.jpg", 
		link: "https://www.disneyplus.com/en-gb/browse/entity-d6e23a1a-9e19-4a22-9b63-b0c6a1d4e2e6",
		trailer: "Et4zsoUNb_0"
	}
};

const exploreLists = {
    trending: [
        "KPopDemonHunters", "HomeAlone", "Superman", "F1", "Frankenstein", 
        "Wicked2", "Elf", "HappyGilmore2", "Zootropolis2", "TrainDreams"
    ],
    upcoming: [
        "Avatar3", "Spiderman4", "Odyssey", "ToyStory5", "Scream7", "Frozen3"
    ],
    seasonal: [	
        "ChristmasWithTheKranks", "HomeAlone", "Krampus", "Elf", "HomeAlone2", 
        "TheGrinchIllumination", "DieHard", "PolarExpress", "LoveActually", "ChristmasVacation"
    ]
};